import type {BuildingController} from './building';
import type {PlayerCamera} from './camera';
import type {IslandRenderer} from './renderer';
import {solidCells,recordFor,volumeRay,brushSeed,treeSolidAssets,destructionRule,actionBrush,openingBrush,localPoint,DESTRUCTION,isTree,type SolidRecord,type WorldAction,type WorldPatch,type ActionResult} from '../shared/destruction';
import {SparseVolume,brushRegion,type VolumeMesh} from '../shared/volume';
import type {Point3} from '../shared/rocks';
import {buildProp} from '../shared/object-registry';
import type {CollisionBox} from '../shared/volume-collision';
export class DestructionController {
  right=false;repair=false;active=false;private dismantleAllowed=false;private lastStroke=-Infinity;
  readonly authoritative=new Map<string,SolidRecord>();readonly pending=new Map<string,{request:WorldAction;brush?:ReturnType<typeof actionBrush>;expected?:SolidRecord}>();
  readonly metrics:{stage:string;milliseconds:number}[]=[];
  private predictor?:Worker;private predictions=new Map<string,string>();
  private stopped=false;private abort=new AbortController();private sessionId=crypto.randomUUID();
  private worker?:Worker;private workerBusy=false;private jobId=0;private tasks=new Map<string,SolidRecord>();private current?:{record:SolidRecord;task:'mesh'|'boxes'};private generated=new Map<string,number>();
  private meshes=new Map<string,VolumeMesh[]>();private meshLods=new Map<string,VolumeMesh[][]>();private boxes=new Map<string,CollisionBox[]>();private poses=new Map<string,{from:SolidRecord;to:SolidRecord;time:number}>();
  private worldRevision=-1;private warmDone=new Set<string>();private lastWarm=0;readonly stages=new Map<string,number[]>();
  private workerCache?:{templates:number;bytes:number};
  private generatedVolumes=new Map<string,import('../shared/volume').VolumeState>();
  readonly trace:{time:number;stage:string;details:unknown}[]=[];
  private log(stage:string,details:unknown={}){const entry={time:Math.round(performance.now()),stage,details};this.trace.push(entry);if(this.trace.length>160)this.trace.shift();console.info('[destruction] '+stage+' '+JSON.stringify(details));}
  debugReport(){return {right:this.right,repair:this.repair,pointerLocked:document.pointerLockElement===this.camera.canvas,worldConnected:!!this.building.worldIdentity,workerBusy:this.workerBusy,workerJob:this.current&&{id:this.current.record.id,revision:this.current.record.revision,task:this.current.task},queuedGeometry:this.tasks.size,pendingActions:[...this.pending.values()].map(p=>p.request),performance:this.performanceReport(),trace:[...this.trace]};}
  private beginStroke(){this.lastStroke=performance.now();void this.stroke().catch(error=>{this.log('stroke-error',{error:String(error),stack:error?.stack});this.notify('Destruction failed: '+String(error));});}
  constructor(readonly building:BuildingController,readonly camera:PlayerCamera,readonly renderer:IslandRenderer,readonly notify:(message:string)=>void){
    const options={signal:this.abort.signal},stop=()=>{this.right=false;this.repair=false;this.active=false;};
    camera.canvas.addEventListener('contextmenu',e=>e.preventDefault(),options);
    window.addEventListener('mousedown',e=>{if(e.button!==2)return;this.log('right-down',{pointerLocked:document.pointerLockElement===camera.canvas,target:(e.target as HTMLElement)?.tagName,ready:camera.character.ready,worldConnected:!!building.worldIdentity});if(document.pointerLockElement!==camera.canvas){this.notify('Click the landscape first to capture the mouse');return;}e.preventDefault();this.right=true;this.active=true;this.dismantleAllowed=true;this.beginStroke();},options);
    window.addEventListener('mouseup',e=>{if(e.button===2){this.right=false;this.log('right-up');}},options);
    window.addEventListener('keydown',e=>{if(e.code==='KeyR'&&document.pointerLockElement===camera.canvas){e.preventDefault();if(!this.repair)this.lastStroke=-Infinity;this.repair=true;}},options);
    window.addEventListener('keyup',e=>{if(e.code==='KeyR')this.repair=false;},options);
    window.addEventListener('blur',stop,options);document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==camera.canvas)stop();},options);
  }
  async initialize(){await Promise.all(['oak','birch','palm'].flatMap(kind=>Array.from({length:kind==='palm'?3:6},async(_,i)=>{const key=`${kind}-${i}`;if(treeSolidAssets.has(key))return;const response=await fetch(`/models/${key}-solid.json`);if(!response.ok)throw new Error('Cannot load destructible tree solids');treeSolidAssets.set(key,await response.json());})));this.predictor=new Worker(new URL('./prediction.worker.ts',import.meta.url),{type:'module'});this.predictor.onmessage=e=>{const v=e.data;if(v.error||this.predictions.get(v.record.id)!==v.signature)return;this.building.scene.applyRecord(v.record);this.renderer.predictSolid(v.record,v.regions,v.meshes);};this.worker=new Worker(new URL('./volume.worker.ts',import.meta.url),{type:'module'});this.worker.onmessage=e=>this.complete(e.data);this.worker.onerror=e=>{this.notify('Solid geometry failed: '+e.message);this.workerBusy=false;};}
  accept(patch:WorldPatch,replace=false){
    if(patch.actionId)this.pending.delete(patch.actionId);
    this.worldRevision=Math.max(this.worldRevision,patch.revision);const scene=this.building.scene;
    for(const floor of patch.leveling??[])scene.keepLeveling(floor);for(const o of patch.openings??[])scene.setOpening(o.id,o.kind);for(const id of patch.removedBuilds??[])scene.remove(id,true);
    for(const record of patch.solids??[]){const old=this.authoritative.get(record.id);if(old&&record.revision===old.revision&&record.removed===old.removed&&record.opening===old.opening&&JSON.stringify(record.pose)===JSON.stringify(old.pose)&&JSON.stringify(record.fall)===JSON.stringify(old.fall))continue;if(!old||record.revision>=old.revision){const next=old&&record.revision===old.revision?{...record,source:old.source,volume:old.volume}:record;this.authoritative.set(record.id,next);if(old?.pose&&record.pose)this.poses.set(record.id,{from:old,to:record,time:performance.now()});}}
    this.rebase();
  }
  private rebase(){const scene=this.building.scene;
    for(const record of this.authoritative.values())if(scene.edits.get(record.id)!==record)scene.applyRecord(record);
    const grouped=new Map<string,typeof this.pending extends Map<any,infer V>?V[]:never>();for(const p of this.pending.values()){const a=grouped.get(p.request.targetId)??[];a.push(p);grouped.set(p.request.targetId,a);}
    for(const [id,strokes]of grouped){const r=this.authoritative.get(id);if(!r||r.prop.kind==='terrain')continue; // Terrain waits for the accepted mesh/collision pair; no provisional ground underfoot.
const signature=r.revision+'/'+strokes.map(p=>p.request.requestId).join(',');if(this.predictions.get(id)===signature)continue;this.predictions.set(id,signature);const regions=strokes.filter(p=>p.brush).map(p=>brushRegion(p.brush!));this.renderer.predictSolid(r,regions,[]);this.predictor?.postMessage({record:r,strokes:strokes.map(p=>({action:p.request.action,brush:p.brush})),signature});}
    for(const id of this.predictions.keys())if(!grouped.has(id))this.predictions.delete(id);
    for(const r of this.authoritative.values()){if(r.removed){this.renderer.removeDamagedMesh(r.id);this.generated.delete(r.id);this.generatedVolumes.delete(r.id);this.tasks.delete(r.id);continue;}if(this.generated.get(r.id)!==r.revision)this.tasks.set(r.id,r);}
    this.dispatch();
  }
  private dispatch(){if(this.workerBusy||!this.worker||!this.tasks.size||this.stopped)return;const p=this.camera.position,priority=new Set([...this.pending.values()].map(a=>a.request.targetId));const first=[...this.tasks].sort((a,b)=>{const score=(e:[string,SolidRecord])=>e[0].startsWith('warm:')?1e12:priority.has(e[0])?-1e12:Math.hypot((e[1].pose?.position[0]??e[1].prop.x)-p[0],(e[1].pose?.position[2]??e[1].prop.z)-p[2]);return score(a)-score(b);})[0];this.tasks.delete(first[0]);const task=destructionRule(first[1].prop)?.mode==='whole'?'boxes':'mesh';this.current={record:first[1],task};this.workerBusy=true;if(!first[0].startsWith('warm:'))this.log('geometry-queued',{target:first[0],revision:first[1].revision,task,bricks:Object.keys(first[1].volume.bricks).length});this.worker.postMessage({id:++this.jobId,task,source:first[1].source,state:first[1].volume,lods:Math.hypot(first[1].prop.x-p[0],first[1].prop.z-p[2])>64,warm:first[0].startsWith('warm:'),templateUrl:isTree(first[1].prop)?`/models/solids/${first[1].prop.kind}-${first[1].prop.variant}.contour.gz`:undefined});}
  private complete(value:any){if(value.cache)this.workerCache=value.cache;const job=this.current;if(!job||this.stopped)return;if(!job.record.id.startsWith('warm:'))this.log('geometry-complete',{target:job.record.id,revision:job.record.revision,task:job.task,milliseconds:value.milliseconds,error:value.error});this.metric(job.task,value.milliseconds??0);if(value.error){console.error(value.stack??value.error);this.notify('Solid geometry: '+value.error);this.workerBusy=false;this.dispatch();return;}const current=this.building.scene.edits.get(job.record.id);if(!current||current.removed||current.revision<job.record.revision){this.workerBusy=false;this.dispatch();return;}
    if(current.revision!==job.record.revision||current.volume!==job.record.volume){this.tasks.set(current.id,current);this.workerBusy=false;this.current=undefined;this.dispatch();return;}
    if(job.task==='mesh'){const meshes=value.result as VolumeMesh[];this.renderer.setDamagedMesh(current,meshes,value.lods??[]);this.meshes.set(current.id,meshes);this.meshLods.set(current.id,value.lods??[]);this.generated.set(current.id,current.revision);this.workerBusy=false;this.current=undefined;this.dispatch();return;}
    this.boxes.set(current.id,value.result);this.building.scene.setDamageCollision(current,value.result);this.generated.set(current.id,current.revision);this.generatedVolumes.set(current.id,current.volume);this.workerBusy=false;this.current=undefined;this.dispatch();
  }
  private metric(stage:string,milliseconds:number){const values=this.stages.get(stage)??[];values.push(milliseconds);if(values.length>300)values.shift();this.stages.set(stage,values);this.metrics.push({stage,milliseconds});if(this.metrics.length>300)this.metrics.shift();}
  update(){const now=performance.now();this.active=this.right||this.repair;
    if(!this.active&&now-this.lastWarm>500&&!this.workerBusy&&this.tasks.size===0){this.lastWarm=now;const preview=this.building.preview?.object;let warm:SolidRecord|undefined;try{if(preview){const solid=this.building.scene.solid(buildProp(preview),'warm');warm=recordFor('warm:'+this.building.definitionId,solid.prop,this.building.scene.rocks);}else{const hit=this.building.scene.raycast([...this.camera.position]as Point3,this.camera.forward,12,false,true);if(hit?.solid&&hit.solid.prop.kind!=='terrain'&&destructionRule(hit.solid.prop)?.mode==='voxel'&&!this.building.scene.edits.has(hit.solid.id))warm=recordFor('warm:'+hit.solid.prop.kind+':'+hit.solid.prop.variant,hit.solid.prop,this.building.scene.rocks);}if(warm&&!this.warmDone.has(warm.id)){this.warmDone.add(warm.id);this.tasks.set(warm.id,warm);this.dispatch();}}catch{}}
    for(const [id,entry]of this.poses){const t=Math.min(1,(now-entry.time)/100),from=entry.from.pose!,to=entry.to.pose!,a=from.rotation,b=[...to.rotation];if(a.reduce((s,n,i)=>s+n*b[i],0)<0)for(let i=0;i<4;i++)b[i]*=-1;const q=a.map((n,i)=>n+(b[i]-n)*t),length=Math.hypot(...q)||1,record={...entry.to,pose:{position:from.position.map((n,i)=>n+(to.position[i]-n)*t)as Point3,rotation:q.map(n=>n/length)as [number,number,number,number]}};this.building.scene.edits.set(id,record);if(this.boxes.has(id)&&t>=1&&(this.building.definitionId||!entry.from.fall?.settled&&record.fall?.settled))this.building.scene.setDamageCollision(record,this.boxes.get(id)!);this.renderer.updateDamagedPose(record);if(t>=1)this.poses.delete(id);}
    if(!this.active||document.pointerLockElement!==this.camera.canvas||now-this.lastStroke<DESTRUCTION.intervalMs)return;this.beginStroke();
  }
  async stroke(){const inputStart=performance.now(),scene=this.building.scene,eye=[...this.camera.position]as Point3,direction=this.camera.forward,hit=scene.raycast(eye,direction,DESTRUCTION.reach,this.repair,true);if(!hit?.solid){this.log('no-target',{eye,direction,reach:DESTRUCTION.reach,hit:hit&&{point:hit.point,distance:hit.distance,kind:'terrain'}});this.notify('Aim at ground, solid wood, rock, or a build within 4 m');return;}const solid=hit.solid,rule=destructionRule(solid.prop);this.log('target',{id:solid.id,kind:solid.prop.kind,distance:hit.distance,point:hit.point,revision:scene.edits.get(solid.id)?.revision??0,rule});if(!rule){this.log('not-destructible',{kind:solid.prop.kind});return;}if(this.repair&&(!solid.object||!rule.repairable)){this.notify('Repair built walls, floors, and roofs');return;}const whole=rule.mode==='whole';if(whole&&!this.repair&&!this.dismantleAllowed)return;if(whole&&!this.repair)this.dismantleAllowed=false;if(!this.building.worldIdentity){this.log('server-not-ready');this.notify('Waiting for the world server');return;}
    let record=scene.edits.get(solid.id)??solid.record??recordFor(solid.id,solid.prop,scene.rocks,solid.object);if(!this.authoritative.has(record.id))this.authoritative.set(record.id,record);
    const request:WorldAction={action:this.repair?'repair':whole?'dismantle':'cut',requestId:crypto.randomUUID(),sessionId:this.sessionId,worldKey:this.building.worldIdentity,targetId:solid.id,targetRevision:(this.authoritative.get(record.id)?.revision??record.revision)+[...this.pending.values()].filter(p=>p.request.targetId===record.id).length,eye,direction,feet:[...this.camera.character.feet]as Point3};
    const brush=whole?undefined:actionBrush(record,hit.point,direction,this.repair,brushSeed(request.requestId));if(record.opening&&!scene.edits.has(record.id)){const volume=new SparseVolume(record.source,record.volume);volume.edit(openingBrush(record,record.opening));record={...record,volume:volume.state};this.authoritative.set(record.id,record);}
    document.querySelector('.reticle')?.animate([{borderColor:this.repair?'#b9f3ce':'#ffda9b',transform:'scale(2)'},{borderColor:'#ffffffba',transform:'scale(1)'}],{duration:180});this.pending.set(request.requestId,{request,brush});this.rebase();this.metric('input-to-visible-commit',performance.now()-inputStart);const start=performance.now();
    void(async()=>{try{
      const base=this.authoritative.get(request.targetId),pending=this.pending.get(request.requestId);

      this.log('action-sent',{action:request.action,requestId:request.requestId,target:request.targetId,revision:request.targetRevision});const result=await this.building.network!.command('action',request) as ActionResult;this.log('action-response',{requestId:request.requestId,result:result.ok?'confirmed':result.code,error:result.ok?undefined:result.error,milliseconds:Math.round(performance.now()-start)});
      if(result.ok){this.pending.delete(request.requestId);this.accept(result.patch);}else{this.pending.delete(request.requestId);this.rebase();if(result.code!=='cadence'&&result.code!=='revision')this.notify(result.error);void this.building.sync();}
    }catch(error){this.log('action-network-error',{requestId:request.requestId,error:String(error)});this.pending.delete(request.requestId);this.rebase();if(!this.stopped)this.notify('Confirmation lost; refreshing world state');}finally{this.metric('confirmation',performance.now()-start);}})();
  }
  acceptCollisions(collisions:{id:string;revision:number;boxes:CollisionBox[]}[]){for(const c of collisions){const r=this.authoritative.get(c.id);if(r&&!r.removed&&r.revision===c.revision){this.boxes.set(c.id,c.boxes);this.building.scene.setDamageCollision(r,c.boxes);}}}
  acceptMotion(message:any){for(const state of message.states){const old=this.authoritative.get(state.id);if(!old||old.removed||old.revision!==state.revision)continue;const to={...old,pose:state.pose,fall:state.fall};this.authoritative.set(state.id,to);const from=this.building.scene.edits.get(state.id)??old;if(from.pose&&to.pose)this.poses.set(state.id,{from,to,time:performance.now()});else{this.building.scene.edits.set(state.id,to);this.renderer.updateDamagedPose(to);}}}
  evict(wanted:Set<string>){for(const id of this.building.scene.openings.keys())if(!this.building.scene.placed.get(id)&&!this.authoritative.has(id))this.building.scene.openings.delete(id);for(const [id,floor]of this.building.scene.leveling)if(!wanted.has(`${Math.floor(floor.position[0]/512)}:${Math.floor(floor.position[2]/512)}`))this.building.scene.forgetLeveling(id);for(const [id,r]of this.authoritative){const p=r.pose?.position??[r.prop.x,r.prop.y,r.prop.z];if(!solidCells(r).some(k=>wanted.has(k))&&![...this.pending.values()].some(p=>p.request.targetId===id)){this.authoritative.delete(id);this.building.scene.edits.delete(id);this.building.scene.damageCollision.delete(id);this.generated.delete(id);this.generatedVolumes.delete(id);this.meshes.delete(id);this.meshLods.delete(id);this.boxes.delete(id);this.tasks.delete(id);this.renderer.removeDamagedMesh(id);this.building.scene.editedCollisionReady.delete(id);}}}
  performanceReport(){return {stages:Object.fromEntries([...this.stages].map(([stage,values])=>{const v=[...values].sort((a,b)=>a-b);return [stage,{samples:v.length,meanMs:v.reduce((n,t)=>n+t,0)/v.length,p95Ms:v[Math.max(0,Math.ceil(v.length*.95)-1)]}];})),network:this.building.network?.metrics,workerCache:this.workerCache,residentGeometryBytes:[...[...this.meshes.values()].flat(),...[...this.meshLods.values()].flat(2)].reduce((n,m)=>n+m.vertices.byteLength+m.indices.byteLength,0),residentSolids:this.authoritative.size,pending:this.pending.size};}
  dispose(){this.stopped=true;this.abort.abort();this.worker?.terminate();this.predictor?.terminate();this.pending.clear();this.tasks.clear();this.meshes.clear();this.meshLods.clear();this.boxes.clear();this.generatedVolumes.clear();}
}
