import type {BuildingController} from './building';
import type {PlayerCamera} from './camera';
import type {IslandRenderer} from './renderer';
import {SolidPhysics,initializePhysics} from '../shared/solid-physics';
import {recordFor,volumeRay,brushSeed,treeSolidAssets,destructionRule,actionBrush,openingBrush,localPoint,predictionDigest,DESTRUCTION,isTree,type SolidRecord,type WorldAction,type WorldPatch,type ActionReply,type ActionAcknowledgement} from '../shared/destruction';
import {SparseVolume,brushRegion,type VolumeMesh} from '../shared/volume';
import type {Point3} from '../shared/rocks';
import {buildProp} from '../shared/object-registry';
import type {CollisionBox} from '../shared/volume-collision';
export class DestructionController {
  right=false;repair=false;active=false;private dismantleAllowed=false;private lastStroke=-Infinity;
  readonly authoritative=new Map<string,SolidRecord>();readonly pending=new Map<string,{request:WorldAction;brush?:ReturnType<typeof actionBrush>;expected?:SolidRecord}>();
  readonly network={sentBytes:0,receivedBytes:0,messages:0};
  readonly metrics:{stage:string;milliseconds:number}[]=[];
  private socket?:WebSocket;private socketRetry=0;private subscription='';private stopped=false;private abort=new AbortController();private queue=Promise.resolve();private sessionId=crypto.randomUUID();
  private worker?:Worker;private workerBusy=false;private jobId=0;private tasks=new Map<string,SolidRecord>();private current?:{record:SolidRecord;task:'mesh'|'boxes'};private generated=new Map<string,number>();
  private colliderMeshes=new Map<string,VolumeMesh[]>();private meshes=new Map<string,VolumeMesh[]>();private meshLods=new Map<string,VolumeMesh[][]>();private boxes=new Map<string,CollisionBox[]>();private physics?:SolidPhysics;private physicsOrigin='';private poses=new Map<string,{from:SolidRecord;to:SolidRecord;time:number}>();
  private lastPose=0;private worldRevision=-1;private warmDone=new Set<string>();private lastWarm=0;readonly stages=new Map<string,number[]>();
  private workerCache?:{templates:number;bytes:number};
  private generatedVolumes=new Map<string,string>();
  readonly trace:{time:number;stage:string;details:unknown}[]=[];
  private log(stage:string,details:unknown={}){const entry={time:Math.round(performance.now()),stage,details};this.trace.push(entry);if(this.trace.length>160)this.trace.shift();console.info('[destruction] '+stage+' '+JSON.stringify(details));}
  debugReport(){return {right:this.right,repair:this.repair,pointerLocked:document.pointerLockElement===this.camera.canvas,worldConnected:!!this.building.worldIdentity,workerBusy:this.workerBusy,workerJob:this.current&&{id:this.current.record.id,revision:this.current.record.revision,task:this.current.task},queuedGeometry:this.tasks.size,pendingActions:[...this.pending.values()].map(p=>p.request),performance:this.performanceReport(),trace:[...this.trace]};}
  private beginStroke(){this.lastStroke=performance.now();void this.stroke().catch(error=>{this.log('stroke-error',{error:String(error),stack:error?.stack});this.notify('Destruction failed: '+String(error));});}
  constructor(readonly building:BuildingController,readonly camera:PlayerCamera,readonly renderer:IslandRenderer,readonly notify:(message:string)=>void){
    const options={signal:this.abort.signal},stop=()=>{this.right=false;this.repair=false;this.active=false;};
    camera.canvas.addEventListener('contextmenu',e=>e.preventDefault(),options);
    window.addEventListener('mousedown',e=>{if(e.button!==2)return;this.log('right-down',{pointerLocked:document.pointerLockElement===camera.canvas,target:(e.target as HTMLElement)?.tagName,ready:camera.character.ready,worldConnected:!!building.worldIdentity});if(document.pointerLockElement!==camera.canvas){this.notify('Click the landscape first to capture the mouse');return;}e.preventDefault();this.right=true;this.active=true;this.dismantleAllowed=true;this.beginStroke();},options);
    window.addEventListener('mouseup',e=>{if(e.button===2){this.right=false;this.log('right-up');}},options);
    window.addEventListener('keydown',e=>{if(e.code==='KeyR'&&document.pointerLockElement===camera.canvas){e.preventDefault();if(!this.repair)this.lastStroke=-Infinity;this.repair=true;}},options);
    window.addEventListener('keyup',e=>{if(e.code==='KeyR')this.repair=false;},options);
    window.addEventListener('blur',stop,options);document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==camera.canvas)stop();},options);
  }
  async initialize(){await initializePhysics();await Promise.all(['oak','birch','palm'].flatMap(kind=>Array.from({length:kind==='palm'?3:6},async(_,i)=>{const key=`${kind}-${i}`;if(treeSolidAssets.has(key))return;const response=await fetch(`/models/${key}-solid.json`);if(!response.ok)throw new Error('Cannot load destructible tree solids');treeSolidAssets.set(key,await response.json());})));this.worker=new Worker(new URL('./volume.worker.ts',import.meta.url),{type:'module'});this.worker.onmessage=e=>this.complete(e.data);this.worker.onerror=e=>{this.notify('Solid geometry failed: '+e.message);this.workerBusy=false;};}
  accept(patch:WorldPatch,replace=false){
    if(patch.actionId)this.pending.delete(patch.actionId);
    if(patch.revision<this.worldRevision&&!replace){this.rebase();return;}this.worldRevision=Math.max(this.worldRevision,patch.revision);const scene=this.building.scene;
    for(const floor of patch.leveling??[])scene.keepLeveling(floor);for(const o of patch.openings??[])scene.setOpening(o.id,o.kind);for(const id of patch.removedBuilds??[])scene.remove(id,true);
    for(const record of patch.solids??[]){const old=this.authoritative.get(record.id);if(old&&record.revision===old.revision&&record.removed===old.removed&&record.opening===old.opening&&JSON.stringify(record.pose)===JSON.stringify(old.pose)&&JSON.stringify(record.fall)===JSON.stringify(old.fall))continue;if(!old||record.revision>=old.revision){const next=old&&record.revision===old.revision?{...record,source:old.source,volume:old.volume}:record;this.authoritative.set(record.id,next);if(old?.pose&&record.pose)this.poses.set(record.id,{from:old,to:record,time:performance.now()});}}
    this.rebase();
  }
  private acknowledge(result:ActionAcknowledgement){
    const pending=this.pending.get(result.requestId),expected=pending?.expected;if(!pending||!expected)return;
    if(expected.id!==result.ack.targetId||expected.revision!==result.ack.targetRevision||predictionDigest(expected)!==result.ack.prediction){this.pending.delete(result.requestId);this.rebase();void this.building.sync();return;}
    const old=this.authoritative.get(expected.id);if(!old||old.revision<expected.revision)this.authoritative.set(expected.id,expected);
    this.worldRevision=Math.max(this.worldRevision,result.ack.revision);this.pending.delete(result.requestId);this.rebase();
  }
  private rebase(){const scene=this.building.scene;for(const record of this.authoritative.values())if(scene.edits.get(record.id)!==record)scene.applyRecord(record);
    for(const pending of this.pending.values()){const {request,brush}=pending,before=scene.edits.get(request.targetId);if(!before)continue;if(request.action==='dismantle')scene.applyRecord({...before,removed:true,revision:before.revision+1});else if(brush){const volume=new SparseVolume(before.source,before.volume,true);volume.edit(brush,request.action==='repair');pending.expected={...before,volume:volume.state,revision:before.revision+1};scene.applyRecord(pending.expected);}}
    for(const r of scene.edits.values()){if(r.removed){this.renderer.removeDamagedMesh(r.id);this.physics?.remove(r.id);this.generated.delete(r.id);this.generatedVolumes.delete(r.id);this.tasks.delete(r.id);continue;}const regions=[...this.pending.values()].filter(p=>p.request.targetId===r.id&&p.brush).map(p=>brushRegion(p.brush!)),latency=this.renderer.predictSolid(r,regions);if(latency!==undefined)this.metric('prediction',latency);if(this.generated.get(r.id)!==r.revision||this.generatedVolumes.get(r.id)!==JSON.stringify(r.volume))this.tasks.set(r.id,r);}
    this.dispatch();
  }
  private dispatch(){if(this.workerBusy||!this.worker||!this.tasks.size||this.stopped)return;const p=this.camera.position,priority=new Set([...this.pending.values()].map(a=>a.request.targetId));const first=[...this.tasks].sort((a,b)=>{const score=(e:[string,SolidRecord])=>e[0].startsWith('warm:')?1e12:priority.has(e[0])?-1e12:Math.hypot((e[1].pose?.position[0]??e[1].prop.x)-p[0],(e[1].pose?.position[2]??e[1].prop.z)-p[2]);return score(a)-score(b);})[0];this.tasks.delete(first[0]);const task=destructionRule(first[1].prop)?.mode==='whole'?'boxes':'mesh';this.current={record:first[1],task};this.workerBusy=true;if(!first[0].startsWith('warm:'))this.log('geometry-queued',{target:first[0],revision:first[1].revision,task,bricks:Object.keys(first[1].volume.bricks).length});this.worker.postMessage({id:++this.jobId,task,source:first[1].source,state:first[1].volume,warm:first[0].startsWith('warm:'),templateUrl:isTree(first[1].prop)?`/models/solids/${first[1].prop.kind}-${first[1].prop.variant}.contour.gz`:undefined});}
  private complete(value:any){if(value.cache)this.workerCache=value.cache;const job=this.current;if(!job||this.stopped)return;if(!job.record.id.startsWith('warm:'))this.log('geometry-complete',{target:job.record.id,revision:job.record.revision,task:job.task,milliseconds:value.milliseconds,error:value.error});this.metric(job.task,value.milliseconds??0);if(value.error){console.error(value.stack??value.error);this.notify('Solid geometry: '+value.error);this.workerBusy=false;this.dispatch();return;}const current=this.building.scene.edits.get(job.record.id);if(!current||current.removed||current.revision<job.record.revision){this.workerBusy=false;this.dispatch();return;}
    if(current.revision!==job.record.revision||JSON.stringify(current.volume)!==JSON.stringify(job.record.volume)){this.tasks.set(current.id,current);this.workerBusy=false;this.current=undefined;this.dispatch();return;}
    if(job.task==='mesh'){const meshes=value.result as VolumeMesh[];this.renderer.setDamagedMesh(current,meshes,value.lods??[]);this.meshes.set(current.id,meshes);this.colliderMeshes.set(current.id,value.colliders??meshes);this.meshLods.set(current.id,value.lods??[]);this.current={record:job.record,task:'boxes'};this.worker!.postMessage({id:++this.jobId,task:'boxes',source:job.record.source,state:job.record.volume,step:isTree(job.record.prop)?.1:.05});return;}
    this.boxes.set(current.id,value.result);this.building.scene.setDamageCollision(current,value.result);this.generated.set(current.id,current.revision);this.generatedVolumes.set(current.id,JSON.stringify(current.volume));this.ensurePhysics();const installStart=performance.now();this.install(current);this.building.scene.editedCollisionReady.add(current.id);this.metric('collider-install',performance.now()-installStart);this.workerBusy=false;this.current=undefined;this.dispatch();
  }
  private metric(stage:string,milliseconds:number){const values=this.stages.get(stage)??[];values.push(milliseconds);if(values.length>300)values.shift();this.stages.set(stage,values);this.metrics.push({stage,milliseconds});if(this.metrics.length>300)this.metrics.shift();}
  private ensurePhysics(){const p=this.camera.position,origin:Point3=[Math.floor(p[0]/512)*512,Math.floor(p[1]/256)*256,Math.floor(p[2]/512)*512],key=origin.join(':');if(this.physicsOrigin===key)return;this.physics?.dispose();this.physics=new SolidPhysics(origin);this.physicsOrigin=key;for(const r of this.building.scene.edits.values())if(!r.removed)this.install(r);}
  private install(record:SolidRecord){if(!this.physics||record.removed||!this.boxes.has(record.id))return;const p=record.pose?.position??[record.prop.x,record.prop.y,record.prop.z];if(Math.hypot(p[0]-this.camera.position[0],p[2]-this.camera.position[2])>96)return;this.physics.add(record,this.boxes.get(record.id)!,record.fall&&!record.fall.settled?undefined:this.colliderMeshes.get(record.id),false);}
  movement(feet:Point3,desired:Point3,radius:number,height:number,step:number,snap:number){if(!this.physics||!this.physics.solids.size)return null;const start=performance.now(),result=this.physics.movement(feet,desired,radius,height,step,snap);this.metric('capsule',performance.now()-start);return result;}
  update(){const now=performance.now();this.active=this.right||this.repair;
    if(!this.active&&now-this.lastWarm>500&&!this.workerBusy&&this.tasks.size===0){this.lastWarm=now;const preview=this.building.preview?.object;let warm:SolidRecord|undefined;try{if(preview){const solid=this.building.scene.solid(buildProp(preview),'warm');warm=recordFor('warm:'+this.building.definitionId,solid.prop,this.building.scene.rocks);}else{const hit=this.building.scene.raycast([...this.camera.position]as Point3,this.camera.forward,12,false,true);if(hit?.solid&&destructionRule(hit.solid.prop)?.mode==='voxel'&&!this.building.scene.edits.has(hit.solid.id))warm=recordFor('warm:'+hit.solid.prop.kind+':'+hit.solid.prop.variant,hit.solid.prop,this.building.scene.rocks);}if(warm&&!this.warmDone.has(warm.id)){this.warmDone.add(warm.id);this.tasks.set(warm.id,warm);this.dispatch();}}catch{}}
    if(this.building.worldIdentity&&!this.socket&&now>this.socketRetry)this.connect();if(this.socket?.readyState===WebSocket.OPEN){if(now-this.lastPose>200){this.lastPose=now;this.socket.send(JSON.stringify({type:'pose',sessionId:this.sessionId,feet:[...this.camera.character.feet]}));}const cells=this.building.visibleCells(),signature=cells.join(',');if(signature!==this.subscription){this.subscription=signature;this.socket.send(JSON.stringify({type:'subscribe',cells}));}}
    if(this.physics){this.ensurePhysics();for(const [id,s]of this.physics.solids){const r=this.building.scene.edits.get(id),p=r?.pose?.position??(r&&[r.prop.x,r.prop.y,r.prop.z]);if(!r||r.removed||p&&Math.hypot(p[0]-this.camera.position[0],p[2]-this.camera.position[2])>110)this.physics.remove(id);}for(const r of this.building.scene.edits.values())if(!r.removed&&!this.physics.solids.has(r.id)&&this.generated.get(r.id)===r.revision)this.install(r);}
    for(const [id,entry]of this.poses){const t=Math.min(1,(now-entry.time)/60),from=entry.from.pose!,to=entry.to.pose!,a=from.rotation,b=[...to.rotation];if(a.reduce((s,n,i)=>s+n*b[i],0)<0)for(let i=0;i<4;i++)b[i]*=-1;const q=a.map((n,i)=>n+(b[i]-n)*t),length=Math.hypot(...q)||1,record={...entry.to,pose:{position:from.position.map((n,i)=>n+(to.position[i]-n)*t)as Point3,rotation:q.map(n=>n/length)as [number,number,number,number]}};this.building.scene.edits.set(id,record);this.physics?.pose(record);if(this.boxes.has(id)&&t>=1&&(this.building.definitionId||!entry.from.fall?.settled&&record.fall?.settled))this.building.scene.setDamageCollision(record,this.boxes.get(id)!);if(!entry.from.fall?.settled&&record.fall?.settled)this.install(record);this.renderer.updateDamagedPose(record);if(t>=1)this.poses.delete(id);}
    if(!this.active||document.pointerLockElement!==this.camera.canvas||now-this.lastStroke<DESTRUCTION.intervalMs)return;this.beginStroke();
  }
  async stroke(){const inputStart=performance.now(),scene=this.building.scene,eye=[...this.camera.position]as Point3,direction=this.camera.forward,hit=scene.raycast(eye,direction,DESTRUCTION.reach,this.repair,true);if(!hit?.solid){this.log('no-target',{eye,direction,reach:DESTRUCTION.reach,hit:hit&&{point:hit.point,distance:hit.distance,kind:'terrain'}});this.notify('Aim at solid wood, rock, or a build within 4 m');return;}const solid=hit.solid,rule=destructionRule(solid.prop);this.log('target',{id:solid.id,kind:solid.prop.kind,distance:hit.distance,point:hit.point,revision:scene.edits.get(solid.id)?.revision??0,rule});if(!rule){this.log('not-destructible',{kind:solid.prop.kind});return;}if(this.repair&&(!solid.object||!rule.repairable)){this.notify('Repair built walls, floors, and roofs');return;}const whole=rule.mode==='whole';if(whole&&!this.repair&&!this.dismantleAllowed)return;if(whole&&!this.repair)this.dismantleAllowed=false;if(!this.building.worldIdentity){this.log('server-not-ready');this.notify('Waiting for the world server');return;}
    let record=scene.edits.get(solid.id)??recordFor(solid.id,solid.prop,scene.rocks,solid.object);if(!this.authoritative.has(record.id))this.authoritative.set(record.id,record);
    const request:WorldAction={action:this.repair?'repair':whole?'dismantle':'cut',requestId:crypto.randomUUID(),sessionId:this.sessionId,worldKey:this.building.worldIdentity,targetId:solid.id,targetRevision:record.revision,eye,direction,feet:[...this.camera.character.feet]as Point3};
    const brush=whole?undefined:actionBrush(record,hit.point,direction,this.repair,brushSeed(request.requestId));if(record.opening&&!scene.edits.has(record.id)){const volume=new SparseVolume(record.source,record.volume);volume.edit(openingBrush(record,record.opening));record={...record,volume:volume.state};this.authoritative.set(record.id,record);}
    document.querySelector('.reticle')?.animate([{borderColor:this.repair?'#b9f3ce':'#ffda9b',transform:'scale(2)'},{borderColor:'#ffffffba',transform:'scale(1)'}],{duration:180});this.pending.set(request.requestId,{request,brush});this.rebase();this.metric('input-to-visible-commit',performance.now()-inputStart);const start=performance.now();
    this.queue=this.queue.then(async()=>{try{
      const base=this.authoritative.get(request.targetId),pending=this.pending.get(request.requestId);request.targetRevision=base?.revision??0;
      if(base&&brush&&pending?.expected&&pending.expected.revision===base.revision+1)request.prediction=predictionDigest(pending.expected);
      this.log('action-sent',{action:request.action,requestId:request.requestId,target:request.targetId,revision:request.targetRevision});const body=JSON.stringify(request);this.network.sentBytes+=new TextEncoder().encode(body).length;const response=await fetch('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body,signal:AbortSignal.any([this.abort.signal,AbortSignal.timeout(12000)])}),payload=await response.text();this.network.receivedBytes+=new TextEncoder().encode(payload).length;const result=JSON.parse(payload)as ActionReply;this.log('action-response',{requestId:request.requestId,status:response.status,result:result.ok?('ack'in result?'confirmed':'corrected'):result.code,error:result.ok?undefined:result.error,milliseconds:Math.round(performance.now()-start)});
      if(result.ok&&'ack'in result)this.acknowledge(result);else{this.pending.delete(request.requestId);if(result.ok)this.accept(result.patch);else{this.rebase();if(result.code!=='cadence'&&result.code!=='revision')this.notify(result.error);void this.building.sync();}}
    }catch(error){this.log('action-network-error',{requestId:request.requestId,error:String(error)});this.pending.delete(request.requestId);this.rebase();if(!this.stopped)this.notify('Change could not be confirmed · undone');}finally{this.metric('confirmation',performance.now()-start);}});
  }
  private connect(){if(this.stopped)return;const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/events`);this.socket=socket;socket.onopen=()=>{this.subscription='';socket.send(JSON.stringify({type:'pose',sessionId:this.sessionId,feet:[...this.camera.character.feet]}));};socket.onclose=()=>{if(this.socket===socket)this.socket=undefined;this.socketRetry=performance.now()+2000;};socket.onerror=()=>socket.close();socket.onmessage=e=>{this.network.messages++;this.network.receivedBytes+=new TextEncoder().encode(e.data).length;try{const message=JSON.parse(e.data);if(message.worldKey&&message.worldKey!==this.building.worldIdentity)return;if(message.type==='ack'){this.acknowledge(message.result);}else if(message.type==='patch'||message.type==='snapshot'){this.accept(message.patch);if(message.type==='patch')void this.building.sync();}else if(message.type==='motion')for(const state of message.states){const old=this.authoritative.get(state.id);if(!old||old.removed)continue;const to={...old,pose:state.pose,fall:state.fall};this.authoritative.set(state.id,to);const from=this.building.scene.edits.get(state.id)??old;if(from.pose&&to.pose)this.poses.set(state.id,{from,to,time:performance.now()});else{this.building.scene.edits.set(state.id,to);this.physics?.pose(to);this.renderer.updateDamagedPose(to);}}}catch{this.notify('World update failed · reconnecting');socket.close();}};}
  evict(wanted:Set<string>){for(const id of this.building.scene.openings.keys())if(!this.building.scene.placed.get(id)&&!this.authoritative.has(id))this.building.scene.openings.delete(id);for(const [id,floor]of this.building.scene.leveling)if(!wanted.has(`${Math.floor(floor.position[0]/512)}:${Math.floor(floor.position[2]/512)}`))this.building.scene.forgetLeveling(id);for(const [id,r]of this.authoritative){const p=r.pose?.position??[r.prop.x,r.prop.y,r.prop.z];if(!wanted.has(`${Math.floor(p[0]/512)}:${Math.floor(p[2]/512)}`)&&!wanted.has(`${Math.floor(r.prop.x/512)}:${Math.floor(r.prop.z/512)}`)&&![...this.pending.values()].some(p=>p.request.targetId===id)){this.authoritative.delete(id);this.building.scene.edits.delete(id);this.building.scene.damageCollision.delete(id);this.generated.delete(id);this.generatedVolumes.delete(id);this.meshes.delete(id);this.colliderMeshes.delete(id);this.meshLods.delete(id);this.boxes.delete(id);this.tasks.delete(id);this.physics?.remove(id);this.renderer.removeDamagedMesh(id);this.building.scene.editedCollisionReady.delete(id);}}}
  performanceReport(){return {stages:Object.fromEntries([...this.stages].map(([stage,values])=>{const v=[...values].sort((a,b)=>a-b);return [stage,{samples:v.length,meanMs:v.reduce((n,t)=>n+t,0)/v.length,p95Ms:v[Math.floor((v.length-1)*.95)]}];})),network:this.network,workerCache:this.workerCache,residentGeometryBytes:[...[...this.meshes.values()].flat(),...[...this.meshLods.values()].flat(2),...[...this.colliderMeshes.values()].flat()].reduce((n,m)=>n+m.vertices.byteLength+m.indices.byteLength,0),residentSolids:this.authoritative.size,physicsSolids:this.physics?.solids.size??0,pending:this.pending.size};}
  dispose(){this.stopped=true;this.abort.abort();this.socket?.close();this.worker?.terminate();this.physics?.dispose();this.pending.clear();this.tasks.clear();this.meshes.clear();this.colliderMeshes.clear();this.meshLods.clear();this.boxes.clear();this.generatedVolumes.clear();}
}
