import {describe,it,expect,vi} from 'vitest';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {BuildScene} from '../shared/build-scene';
import {BuildStore} from '../server/build-store';
import {solvePlacement} from '../shared/build-placement';
import {doorChange,validDoorRequest} from '../shared/door-interaction';
import {catalogueChoices,hotbarSlots,objectRegistry,objectDefinition,buildProp,validBuildObject,type BuildObject,type BuildRequest,type DoorRequest} from '../shared/object-registry';
import {CHARACTER,Character,idleInput,characterInput} from '../shared/character';
import {loadGLB} from '../client/glb';
import {mergeGeometry,slabGeometry} from '../client/catalogue-geometry';
import {wallGeometry} from '../client/wall-geometry';
import {wallContains} from '../shared/wall-collision';
import type {WorldGenerator} from '../shared/world';
import type {Point3} from '../shared/rocks';
import {gradedChunk} from '../shared/build-terrain';
import {GRID,VERTEX_FLOATS,type ChunkData} from '../shared/mesh';
import {surfaceOnMesh} from '../shared/placement';
import {packLighting,LIGHTING_FLOATS} from '../client/lighting';
import {daylightLighting} from '../shared/daylight';
const flat=(height=(x:number,z:number)=>0)=>new BuildScene({config:{seed:'catalogue-test',islandSizeMeters:1024},height,props:()=>[],surfaceWater:()=>null}as unknown as WorldGenerator);
const obj=(id:string,definitionId:string,position:Point3=[0,-.1,0],support:BuildObject['support']={kind:'terrain'}):BuildObject=>({id,definitionId,position,support,normal:[0,1,0],rotation:0,variant:0});
function aim(definitionId:string,target:Point3=[0,0,0],feet:Point3=[0,0,4]):BuildRequest{const eye:Point3=[feet[0],feet[1]+CHARACTER.eyeHeight,feet[2]],v=target.map((p,i)=>p-eye[i]),l=Math.hypot(...v);return {requestId:crypto.randomUUID(),definitionId,variant:0,rotation:0,feet,eye,direction:v.map(n=>n/l)as Point3,standing:true};}
describe('catalogue foundations',()=>{
  it('groups all definitions, cycles deterministically, and preserves an empty ninth slot',()=>{expect(hotbarSlots).toHaveLength(9);expect(hotbarSlots[8]).toBeNull();const choices=hotbarSlots.flatMap((_,i)=>catalogueChoices(i));for(const d of objectRegistry.values())expect(choices.filter(c=>c.definitionId===d.id)).toHaveLength(d.variants.length);expect(catalogueChoices(2).map(c=>c.definitionId)).toEqual(['wall-wood','wall-stone','wall-log','wall-brick']);});
  it('loads all Blender assets using finite static geometry and centrally shared materials',async()=>{vi.stubGlobal('fetch',async(url:string)=>new Response(readFileSync('public'+url)));try{const materials=new Set(['wall-wood','wall-stone','oak-bark','linen','iron','ember']);for(const d of objectRegistry.values())if(d.asset){for(const suffix of d.wall?['','-door','-window']:['']){const parts=mergeGeometry(await loadGLB(`/models/${d.id}${suffix}-0-lod0.glb`));expect(parts.length).toBeLessThanOrEqual(3);for(const p of parts){expect(materials.has(p.material)).toBe(true);expect(p.vertices.every(Number.isFinite)).toBe(true);expect(p.indices.every(i=>i<p.vertices.length/16)).toBe(true);}}}}finally{vi.unstubAllGlobals();}},15000);
  it('cuts actual openings into every procedural wall material',()=>{for(const id of ['wall-wood','wall-stone','wall-brick'])for(const opening of ['door','window']as const){const m=wallGeometry(id,opening);for(let i=0;i<m.vertices.length;i+=16){const x=m.vertices[i],y=m.vertices[i+1];expect(Math.abs(x)<(opening==='door'?.58:.65)-.001&&y>(opening==='door'?0:1.05)+.001&&y<(opening==='door'?2.32:2.1)-.001).toBe(false);}}});
  it('flattens modest uneven ground without cumulative excavation and undoes the stamp on removal',()=>{const s=flat(x=>x*.02),p=solvePlacement(s,aim('floor-wood'));expect(p.valid,p.reason).toBe(true);s.add(p.object);expect(s.terrain(0,0).height).toBeLessThan(-.08);for(let x=-5;x<=5;x+=.25)expect(x*.02-s.grade(x,0,x*.02)).toBeLessThanOrEqual(.40001);const before=s.grade(2,0,.04);s.add({...p.object,id:'duplicate-floor'});expect(s.grade(2,0,.04)).toBe(before);s.remove(p.object.id);s.remove('duplicate-floor');expect(s.terrain(0,0).height).toBe(0);});
  it('rejects slopes needing major earthworks and connects floor edges without overlaps',()=>{expect(solvePlacement(flat(x=>x*.5),aim('floor-stone')).valid).toBe(false);const s=flat(),p=solvePlacement(s,aim('floor-wood'));s.add(p.object);const adjacent=solvePlacement(s,aim('floor-stone',[1.49,.10,0],[4,0,3]));expect(adjacent.valid,adjacent.reason).toBe(true);expect(adjacent.object.support).toEqual({kind:'floor',id:p.object.id,socket:'right'});expect(adjacent.object.position[0]).toBeCloseTo(3);});
  it('only accepts connected roofs and snaps a wall to the edge of a floor',()=>{const s=flat();expect(solvePlacement(s,aim('roof-wood')).code).toBe('support');s.add(obj('floor-parent','floor-wood'));const wall=solvePlacement(s,aim('wall-log',[0,.1,1.4],[0,0,4]));expect(wall.valid,wall.reason).toBe(true);expect(wall.object.position[2]).toBeCloseTo(1.5);s.add(wall.object);const roof=solvePlacement(s,aim('roof-wood',[0,1.8,1.5],[0,0,4]));expect(roof.valid,roof.reason).toBe(true);expect(roof.object.position[1]).toBeCloseTo(2.6);s.add(roof.object);expect(roof.object.support.kind).toBe('wall');});
  it('places furniture on whole floor footprints and rejects hanging beyond edges',()=>{const s=flat();s.add(obj('floor-parent','floor-wood'));expect(solvePlacement(s,aim('chair',[0,.1,0])).valid).toBe(true);expect(solvePlacement(s,aim('bed',[1.2,.1,0],[1.2,0,4])).code).toBe('support');});
  it('creates and restores an opening transactionally from its attached door',()=>{const s=flat();s.add(obj('parent-wall','wall-wood'));const door=solvePlacement(s,aim('door-wood',[0,1,0]));expect(door.valid,door.reason).toBe(true);const saved=s.add(door.object);expect(saved.colliders).toHaveLength(1);expect(s.placed.get('parent-wall')!.prop.aperture).toBe('door');expect(s.placed.get('parent-wall')!.colliders).toHaveLength(3);expect(validBuildObject(door.object)).toBe(true);expect(solvePlacement(s,aim('window',[0,1,0])).code).toBe('opening');s.remove(door.object.id);expect(s.placed.get('parent-wall')!.colliders).toHaveLength(1);expect(s.placed.get('parent-wall')!.prop.aperture).toBeUndefined();});
  it('mounts a torch on either wall face and rejects mounting through a window opening',()=>{const s=flat();s.add(obj('parent-wall','wall-stone'));for(const z of [4,-4]){const p=solvePlacement(s,aim('torch-wall',[1,1.5,0],[1,0,z]));expect(p.valid,p.reason).toBe(true);expect(p.object.support).toEqual({kind:'wall',id:'parent-wall',socket:'mount'});expect(Math.sign(p.object.position[2])).toBe(Math.sign(z));}const window=solvePlacement(s,aim('window',[0,1.5,0]));s.add(window.object);expect(solvePlacement(s,aim('torch-wall',[0,1.6,0])).valid).toBe(false);});
  it('saves functional door state without changing the hinge or allowing blocked swings',()=>{const s=flat();s.add(obj('parent-wall','wall-wood'));const p=solvePlacement(s,aim('door-wood',[0,1,0]));s.add(p.object);const a=aim('door-wood',[0,1,0],[0,0,2]),r:DoorRequest={action:'door',requestId:crypto.randomUUID(),objectId:p.object.id,open:true,eye:a.eye,direction:a.direction};expect(validDoorRequest(r)).toBe(true);expect(validDoorRequest({...r,eye:[NaN,0,0]})).toBe(false);const change=doorChange(s,r);expect(change.ok).toBe(true);if(change.ok){s.add(change.object);const prop=buildProp(change.object);expect(prop.x).toBeCloseTo(-.55);expect(prop.z).toBeCloseTo(.55);expect(prop.rotation).toBeCloseTo(Math.PI/2);}const other=flat();other.add(obj('parent-wall','wall-wood'));other.add(p.object);other.add(obj('obstacle','chair',[-.4,0,.7]));expect(doorChange(other,r).ok).toBe(false);});
  it('walks through an opened door but collides with its closed leaf and the jambs',()=>{for(const open of [false,true]){const s=flat();s.add(obj('parent-wall','wall-wood'));s.add({...obj('door-child','door-wood',[0,-.1,0],{kind:'wall',id:'parent-wall',socket:'opening'}),state:{open}});const c=new Character({surface:(x,z)=>s.terrain(x,z),colliders:(x,z)=>s.colliders(x,z)});c.spawn(0,0,2);for(let i=0;i<90;i++)c.update(1/60,characterInput(new Set(['KeyW']),0));if(open)expect(c.feet[2]).toBeLessThan(-1);else expect(c.feet[2]).toBeGreaterThan(.35);}});
  it('steps onto thin floors, lands on roofs and bumps the roof underside when jumping',()=>{const s=flat();s.add(obj('floor-parent','floor-wood'));s.add(obj('roof-parent','roof-wood',[0,2.5,0]));const c=new Character({surface:(x,z)=>s.terrain(x,z),colliders:(x,z)=>s.colliders(x,z)});c.spawn(0,.1,2.2);for(let i=0;i<40;i++)c.update(1/60,characterInput(new Set(['KeyW']),0));expect(c.feet[1]).toBeCloseTo(.1);let max=0;for(let i=0;i<60;i++){c.update(1/60,{...idleInput,jump:i<2});max=Math.max(max,c.feet[1]);}expect(max+CHARACTER.height).toBeLessThanOrEqual(2.501);expect(c.feet[1]).toBeCloseTo(.1);c.spawn(0,3.5,0);for(let i=0;i<90;i++)c.update(1/60,idleInput);expect(c.feet[1]).toBeCloseTo(2.7);});
  it('keeps rotated floor terrain below the slab and renders the same full-detail collision triangles',()=>{const s=flat(x=>x*.025),r={...aim('floor-wood'),rotation:Math.PI/4},p=solvePlacement(s,r);expect(p.valid,p.reason).toBe(true);s.add(p.object);const world=sampleWorld(s),data=chunk(world,-32,-32,0),vertices=gradedChunk(s,world,data,[0,0,0,0]);for(let x=-1.5;x<=1.5;x+=.1)for(let z=-1.5;z<=1.5;z+=.1){const c=Math.SQRT1_2,wx=p.object.position[0]+x*c+z*c,wz=p.object.position[2]-x*c+z*c,canonical=s.terrain(wx,wz).height,rendered=surfaceOnMesh(data,vertices,wx,wz).height;expect(rendered).toBeCloseTo(canonical,5);expect(rendered).toBeLessThanOrEqual(p.object.position[1]+.001);}});
  it('stitches the graded heightfield across different LODs and restores exact vertices after rollback',()=>{const s=flat((x,z)=>x*.003+z*.002);s.add({...obj('edge-floor','floor-wood',[64,.152,30]),rotation:.37});const w=sampleWorld(s),fine=chunk(w,0,0,0),coarse=chunk(w,64,0,1),a=gradedChunk(s,w,fine,[0,1,0,0]),b=gradedChunk(s,w,coarse,[1,1,1,1]);for(let z=0;z<=64;z+=.25)expect(surfaceOnMesh(fine,a,64,z).height).toBeCloseTo(surfaceOnMesh(coarse,b,64,z).height,5);s.remove('edge-floor');expect(gradedChunk(s,w,fine,[0,0,0,0])).toEqual(fine.vertices);});
  it('defaults roofs over the supporting floor, switches sides with R, and connects another roof edge',()=>{const s=flat();s.add(obj('floor-parent','floor-wood'));s.add(obj('wall-parent','wall-wood',[0,.1,1.5],{kind:'floor',id:'floor-parent',socket:'front'}));const r=aim('roof-wood',[0,2.45,1.5],[0,0,4]),a=solvePlacement(s,r),b=solvePlacement(s,{...r,rotation:Math.PI/2});expect(a.valid,a.reason).toBe(true);expect(a.object.position[2]).toBe(0);expect(b.object.position[2]).toBe(3);s.add(a.object);const next=solvePlacement(s,aim('roof-stone',[1.49,2.8,0],[4,0,0]));expect(next.valid,next.reason).toBe(true);expect(next.object.support.kind).toBe('roof');expect(next.object.position[0]).toBe(3);});
  it('rejects a window cut that would remove an already mounted torch support',()=>{const s=flat();s.add(obj('parent-wall','wall-wood'));const torch=solvePlacement(s,aim('torch-wall',[0,1.6,0]));expect(torch.valid,torch.reason).toBe(true);s.add(torch.object);const window=solvePlacement(s,aim('window',[0,1.7,0]));expect(window.code).toBe('overlap');});
  it('keeps mounted light origins on the flame, with unchanged torch power and no self-occluding mounting box',()=>{const s=flat(),torch={...obj('mounted-light','torch-wall',[2,1,3],{kind:'wall',id:'parent-wall',socket:'mount'}),rotation:Math.PI/2};s.add(torch);const values=new Float32Array(LIGHTING_FLOATS);packLighting(values,daylightLighting(0),[0,0,0],s.placed.values(),16,0);expect(values[36]).toBeCloseTo(2.12);expect(values[37]).toBeCloseTo(1.9);expect(values[38]).toBeCloseTo(3);expect(values[33]).toBe(0);expect(objectDefinition('torch-wall').light!.power).toBe(objectDefinition('torch').light!.power);});
});
function sampleWorld(s:BuildScene):WorldGenerator {return {...s.world,sample(x:number,z:number){return {height:s.world.height(x,z),normal:[0,1,0],weights:[0,1,0,0,0,0,0,0],forest:0};}}as WorldGenerator;}
function chunk(w:WorldGenerator,x:number,z:number,level:number):ChunkData {const stride=GRID+1,vertices=new Float32Array((stride**2+stride*4)*VERTEX_FLOATS),step=64*2**level/GRID;for(let iz=0;iz<=GRID;iz++)for(let ix=0;ix<=GRID;ix++){const a=(iz*stride+ix)*VERTEX_FLOATS;vertices.set([ix*step,w.height(x+ix*step,z+iz*step),iz*step,0,1,0],a);}const edges=[Array.from({length:stride},(_,i)=>i),Array.from({length:stride},(_,i)=>i*stride+GRID),Array.from({length:stride},(_,i)=>GRID*stride+GRID-i),Array.from({length:stride},(_,i)=>(GRID-i)*stride)];for(let e=0;e<4;e++)for(let i=0;i<stride;i++){const at=(stride**2+e*stride+i)*VERTEX_FLOATS,a=edges[e][i]*VERTEX_FLOATS;vertices.set(vertices.slice(a,a+VERTEX_FLOATS),at);vertices[at+1]-=1.5;}return {x,z,level,key:`${x}:${z}:${level}`,vertices}as ChunkData;}
