import {readFileSync,existsSync,mkdirSync,openSync,writeSync,fsyncSync,closeSync,fstatSync,ftruncateSync,writeFileSync,renameSync,truncateSync} from 'node:fs';
import {join} from 'node:path';
import {gzipSync,gunzipSync} from 'node:zlib';
import {EditCheckpoints} from './edit-checkpoints';
import {createHash} from 'node:crypto';
import {BuildStore} from './build-store';
import {materialNear,pointInSolid} from '../shared/solid-contact';
import {GeometryJobs} from './geometry-jobs';
import {treeSolidAssets,brushSeed,DESTRUCTION,recordFor,actionBrush,openingBrush,destructionRule,validAction,worldPoint,localPoint,volumeRay,isTree,type SolidRecord,type WorldAction,type WorldPatch,type ActionResult} from '../shared/destruction';
import {SparseVolume,emptyVolume,sourceDistance,type VolumeState} from '../shared/volume';
import {objectDefinition,buildCell,type BuildObject} from '../shared/object-registry';
import type {Point3} from '../shared/rocks';
import type {SolidComponent} from '../shared/solid-components';

interface SavedEdit {schema:1;worldKey:string;requestId:string;fingerprint:string;patch:WorldPatch;analysis?:WorldAction}
/** Authoritative world edits; placement and edit checkpoints preserve old IDs. A
 * checkpoint contains only current bricks/poses, not the history of strokes. */
export class DestructionStore {
  readonly actors=new Map<string,{feet:Point3;touched:number}>();
  updateActor(id:string,feet:Point3){if(typeof id==='string'&&id.length<=100&&Array.isArray(feet)&&feet.length===3&&feet.every(n=>Number.isFinite(n)&&Math.abs(n)<1e8)){this.actors.set(id,{feet,touched:Date.now()});for(const [key,p]of this.actors)if(Date.now()-p.touched>5000)this.actors.delete(key);}}
  revision=0;readonly jobs=new GeometryJobs();readonly listeners=new Set<(patch:WorldPatch)=>void>();
  readonly timings:{stage:string;milliseconds:number}[]=[];
  private receipts=new Map<string,{requestId:string;fingerprint:string;data:string}>();private archive?:EditCheckpoints;private componentCache=new Map<string,{revision:number;components:SolidComponent[]}>();private collisionCache=new Map<string,{revision:number;boxes:import('../shared/volume-collision').CollisionBox[]}>();private cadence=new Map<string,number>();private queue=Promise.resolve();private file?:string;private checkpoint?:string;private records=0;private stopped=false;private supportRunning?:Promise<void>;private supportRequests=new Map<string,WorldAction>();private geometryVersions=new Map<string,number>();private placementEpoch=0;
  constructor(readonly builds:BuildStore,directory?:string){
    for(const kind of ['oak','birch','palm'])for(let i=0;i<(kind==='palm'?3:6);i++){const key=`${kind}-${i}`;if(!treeSolidAssets.has(key))treeSolidAssets.set(key,JSON.parse(readFileSync(new URL(`../public/models/${key}-solid.json`,import.meta.url),'utf8')));}
    if(directory){mkdirSync(directory,{recursive:true});this.archive=new EditCheckpoints(join(directory,'regions'),builds.worldKey);this.file=join(directory,builds.worldKey+'.edits.jsonl');this.checkpoint=join(directory,builds.worldKey+'.edits.snapshot.json');
      if(existsSync(this.checkpoint)){const saved=JSON.parse(readFileSync(this.checkpoint,'utf8'));if(![1,2].includes(saved.schema)||saved.worldKey!==builds.worldKey)throw new Error('Invalid destruction checkpoint');this.apply(saved.patch,false);for(const entry of saved.regions??[])this.archive.register(entry);for(const r of this.archive.load([...this.archive.entries.values()].filter(e=>e.active).map(e=>e.id)))this.builds.scene.edits.set(r.id,r);for(const request of saved.support??[])this.supportRequests.set(request.targetId,request);for(const receipt of saved.receipts??[]){if(receipt.data)this.receipts.set(receipt.requestId,receipt);else this.remember(receipt);}}
      if(existsSync(this.file)){let content=readFileSync(this.file,'utf8');if(content&&!content.endsWith('\n')){const end=content.lastIndexOf('\n')+1;writeFileSync(this.file+'.recovery-'+Date.now(),content.slice(end));content=content.slice(0,end);truncateSync(this.file,Buffer.byteLength(content));}for(const line of content.split('\n').filter(Boolean)){const saved=JSON.parse(line)as SavedEdit;if(saved.schema!==1||saved.worldKey!==builds.worldKey||!saved.patch||!Array.isArray(saved.patch.solids))throw new Error('Invalid destruction journal');if(saved.patch.revision<=this.revision)continue;this.apply(saved.patch,false);this.remember(saved);if(saved.analysis)this.supportRequests.set(saved.analysis.targetId,saved.analysis);this.records++;}}
    }
    if(this.supportRequests.size)setImmediate(()=>this.startSupport());
  }
  private measure(stage:string,start:number){this.timings.push({stage,milliseconds:performance.now()-start});if(this.timings.length>300)this.timings.shift();}
  snapshot(keys:string[]){this.hydrateCells(keys);const wanted=new Set(keys),scene=this.builds.scene;const result={revision:this.revision,solids:[...scene.edits.values()].filter(r=>{const p=r.pose?.position??[r.prop.x,r.prop.y,r.prop.z];return wanted.has(buildCell(p[0],p[2]))||wanted.has(buildCell(r.prop.x,r.prop.z));}),leveling:[...scene.leveling.values()].filter(o=>wanted.has(buildCell(o.position[0],o.position[2]))),openings:[...scene.openings].filter(([id])=>{const r=scene.placed.get(id);return r&&wanted.has(buildCell(r.prop.x,r.prop.z));}).map(([id,kind])=>({id,kind})),removedBuilds:[]};this.pruneResident();return result;}
  action(value:unknown):Promise<ActionResult>{const task=this.queue.then(async()=>{const start=performance.now();try{return await this.perform(value);}finally{this.measure('acknowledgement',start);}});this.queue=task.then(()=>{},()=>{});return task;}
  place(value:unknown):Promise<import('../shared/object-registry').BuildResult>{const task=this.queue.then(async()=>{const input=value as any;if(Array.isArray(input?.eye))this.hydrateNear(input.eye[0],input.eye[2]);await this.prepareCollisions([...this.builds.scene.edits.values()].filter(r=>{const p=r.pose?.position??[r.prop.x,r.prop.y,r.prop.z];return !r.removed&&Math.hypot(p[0]-(input.eye?.[0]??0),p[2]-(input.eye?.[2]??0))<40;}));const before=this.builds.revision,result=this.builds.place(value);if(result.ok){if(this.builds.revision!==before)this.placementEpoch++;this.integratePlacementNow(result.object);}return result;});this.queue=task.then(()=>{},()=>{});return task;}
  integratePlacement(object:BuildObject):Promise<void>{const task=this.queue.then(()=>this.integratePlacementNow(object));this.queue=task.then(()=>{},()=>{});return task;}
  private integratePlacementNow(object:BuildObject){const kind=objectDefinition(object.definitionId).attachment;if(object.support.kind!=='wall'||!['door','window'].includes(kind??''))return;this.hydrateCells([buildCell(object.position[0],object.position[2])]);const scene=this.builds.scene,parent=scene.placed.get(object.support.id),old=scene.edits.get(object.support.id);if(!parent||!old)return;const v=new SparseVolume(old.source,old.volume);if(!v.edit(openingBrush(old,kind as 'door'|'window')))return;const patch:WorldPatch={revision:this.revision+1,solids:[{...old,volume:v.state,opening:kind as 'door'|'window',revision:old.revision+1}],removedBuilds:[],leveling:[],openings:[{id:parent.id,kind:kind as 'door'|'window'}]};this.append({schema:1,worldKey:this.builds.worldKey,requestId:'placement-'+object.id,fingerprint:'placement',patch});this.apply(patch);this.records++;}
  private async perform(value:unknown):Promise<ActionResult>{
    const fail=(code:string,error:string):ActionResult=>({ok:false,code,error});if(!validAction(value))return fail('request','Invalid destruction request');const a=value as WorldAction;
    if(a.worldKey!==this.builds.worldKey)return fail('world','World changed · refresh the game');const fingerprint=createHash('sha256').update(JSON.stringify(a)).digest('hex'),receipt=this.receipts.get(a.requestId);if(receipt)return receipt.fingerprint===fingerprint?{ok:true,patch:JSON.parse(gunzipSync(Buffer.from(receipt.data,'base64')).toString()).patch,requestId:a.requestId}:fail('request-id','Action ID was reused');
    const now=Date.now();if(now-(this.cadence.get(a.sessionId)??-Infinity)<DESTRUCTION.intervalMs-15)return fail('cadence','Wait for the next stroke');
    this.hydrateNear(a.eye[0],a.eye[2]);const scene=this.builds.scene,hit=scene.raycast(a.eye,a.direction,DESTRUCTION.reach,a.action==='repair',true);if(!hit?.solid||hit.solid.id!==a.targetId)return fail('target','Target moved or is out of reach');
    const solid=hit.solid,old=scene.edits.get(solid.id);if((old?.revision??0)!==a.targetRevision)return fail('revision','Target changed · aim again');const rule=destructionRule(solid.prop);if(!rule)return fail('target','This object cannot be destroyed');
    if(a.action==='repair'&&(!solid.object||!rule.repairable||old?.fall))return fail('repair','Only surviving built walls, floors, and roofs can be repaired');
    if(a.action==='dismantle'&&rule.mode!=='whole'||a.action==='cut'&&rule.mode==='whole')return fail('mode','Wrong action for this object');
    const patch:WorldPatch={revision:this.revision+1,actionId:a.requestId,solids:[],removedBuilds:[],leveling:[],openings:[]};let record=old??recordFor(solid.id,solid.prop,scene.rocks,solid.object);
    if(a.action==='dismantle'){
      record={...record,removed:true,revision:record.revision+1};patch.solids.push(record);patch.removedBuilds.push(record.id);
      const o=solid.object;if(o?.support.kind==='wall'&&['door','window'].includes(objectDefinition(o.definitionId).attachment??'')){patch.openings.push({id:o.support.id,kind:objectDefinition(o.definitionId).attachment as 'door'|'window'});const parent=scene.placed.get(o.support.id);if(parent){let r=scene.edits.get(parent.id)??recordFor(parent.id,parent.prop,scene.rocks,parent.object),v=new SparseVolume(r.source,r.volume);v.edit(openingBrush(r,objectDefinition(o.definitionId).attachment as 'door'|'window'));patch.solids.push({...r,opening:objectDefinition(o.definitionId).attachment as 'door'|'window',volume:v.state,revision:r.revision+1});}}
    }else{
      const start=performance.now(),volume=new SparseVolume(record.source,record.volume);if(!old&&record.opening)volume.edit(openingBrush(record,record.opening));
      const brush=actionBrush(record,hit.point,a.direction,a.action==='repair',brushSeed(a.requestId));
      const players=[a.feet,...[...this.actors].filter(([id,p])=>id!==a.sessionId&&Date.now()-p.touched<5000).map(([,p])=>p.feet)];
      const obstacles=a.action==='repair'?scene.nearby(hit.point[0],hit.point[2],1):[];
      const allowed=a.action==='repair'?(p:Point3)=>{const w=worldPoint(record,p);if(players.some(feet=>Math.hypot(w[0]-feet[0],w[2]-feet[2])<.39&&w[1]>feet[1]-.025&&w[1]<feet[1]+2.19))return false;for(const other of obstacles){if(other.id===record.id)continue;if(other.object?.support.kind==='wall'&&other.object.support.id===record.id&&['door','window'].includes(objectDefinition(other.object.definitionId).attachment??'')){const o=openingBrush(record,objectDefinition(other.object.definitionId).attachment as 'door'|'window');if(Math.abs(p[0])<o.box![0]+.025&&Math.abs(p[1]-o.center[1])<o.box![1]+.025)return false;}else if(pointInSolid(other,w))return false;}return true;}:undefined;
      if(!volume.edit(brush,a.action==='repair',allowed))return fail('unchanged',a.action==='repair'?'Nothing repairable here':'No solid material hit');this.measure('edit',start);
      record={...record,volume:volume.state,revision:record.revision+1,fall:record.fall&&{...record.fall,settled:undefined}};
      if(a.action==='repair'&&record.opening&&!scene.placed.query(record.prop.x,record.prop.z,3).some(s=>s.object?.support.kind==='wall'&&s.object.support.id===record.id&&['door','window'].includes(objectDefinition(s.object.definitionId).attachment??''))){const opening=openingBrush(record,record.opening),box=opening.box!;let missing=false;for(let y=opening.center[1]-box[1]+.05;y<opening.center[1]+box[1]&&!missing;y+=.05)for(let x=-box[0]+.05;x<box[0]&&!missing;x+=.05)for(let z=-box[2]/2+.025;z<box[2]/2;z+=.025)if(volume.distance([x,y,z])>0){missing=true;break;}if(!missing){record={...record,opening:undefined};patch.openings.push({id:record.id,kind:null});}}
      patch.solids.push(record);
    }
    if(record.object&&objectDefinition(record.object.definitionId).family==='floor')patch.leveling.push(record.object);
    if(a.action==='repair'){const start=performance.now();try{await this.support(patch,a);}catch(error){if(error instanceof Error&&error.message==='unsupported-repair')return fail('support','Repair from an edge connected to supported material');throw error;}this.measure('support',start);}
    this.cadence.set(a.sessionId,now);for(const [id,time]of this.cadence)if(now-time>60000)this.cadence.delete(id);const saved:SavedEdit={schema:1,worldKey:this.builds.worldKey,requestId:a.requestId,fingerprint,patch,analysis:a.action!=='repair'?a:undefined};
    try{this.append(saved);}catch{return fail('save','The server could not save this change');}this.remember(saved);this.apply(patch,true);if(a.action!=='repair'){this.supportRequests.set(a.targetId,a);setImmediate(()=>this.startSupport());}if(++this.records>=128){try{this.compact();}catch(error){console.error('Edit checkpoint:',error);}}return {ok:true,patch,requestId:a.requestId};
  }
  /** Damage is durable before acknowledgement. Connectivity is queued separately,
   * coalesced per target, and may only publish against the revisions it read. */
  private startSupport(){if(this.stopped||this.supportRunning||!this.supportRequests.size)return;this.supportRunning=this.drainSupport().catch(error=>{if(!this.stopped)console.error('Support analysis:',error);}).finally(()=>{this.supportRunning=undefined;if(!this.stopped&&this.supportRequests.size)setImmediate(()=>this.startSupport());});}
  async flushSupport(){while(!this.stopped&&(this.supportRequests.size||this.supportRunning)){this.startSupport();await this.supportRunning;}}
  private async drainSupport(){while(!this.stopped&&this.supportRequests.size){
    const [id,action]=this.supportRequests.entries().next().value!,record=this.builds.scene.edits.get(id);if(!record){this.supportRequests.delete(id);continue;}
    const patch:WorldPatch={revision:0,solids:[record],removedBuilds:[],leveling:[],openings:[]},reads=new Map<string,number>(),parents=new Map<string,string>(),placement=this.placementEpoch,start=performance.now();
    await this.support(patch,action,reads,parents);this.measure('support',start);if(this.stopped)return;
    const commit=this.queue.then(()=>{
      if(this.stopped)return;
      if(placement!==this.placementEpoch||[...reads].some(([key,version])=>(this.geometryVersions.get(key)??0)!==version))return;
      patch.solids=patch.solids.filter(r=>{const old=this.builds.scene.edits.get(r.id);return !old||r.volume!==old.volume||r.removed!==old.removed;}).map(r=>{const old=this.builds.scene.edits.get(r.id),parent=this.builds.scene.edits.get(parents?.get(r.id)??'');if(old)return {...r,pose:old.pose,fall:old.fall,revision:Math.max(r.revision,old.revision+1)};return parent?.pose?{...r,pose:parent.pose,fall:r.fall&&{...r.fall,velocity:parent.fall?.velocity??r.fall.velocity,angular:parent.fall?.angular??r.fall.angular}}:r;});
      if(patch.solids.length){patch.revision=this.revision+1;const saved:SavedEdit={schema:1,worldKey:this.builds.worldKey,requestId:'support-'+action.requestId,fingerprint:'support',patch};this.append(saved);this.apply(patch);this.records++;}
      if(this.supportRequests.get(id)?.requestId===action.requestId)this.supportRequests.delete(id);
    });this.queue=commit.then(()=>{},()=>{});await commit;
  }}
  private async support(patch:WorldPatch,a:WorldAction,reads?:Map<string,number>,parents?:Map<string,string>){
    const scene=this.builds.scene,changed=patch.solids[0];if(!changed)return;
    const center=changed.pose?.position??[changed.prop.x,changed.prop.y,changed.prop.z],nearby=scene.nearby(center[0],center[2],35).filter(s=>destructionRule(s.prop));
    const records=new Map<string,SolidRecord>(nearby.map(s=>[s.id,scene.edits.get(s.id)??recordFor(s.id,s.prop,scene.rocks,s.object)]));for(const r of patch.solids)records.set(r.id,r);
    const frontier=[...records.values()];for(let i=0;i<frontier.length;i++){const r=frontier[i];for(const s of scene.placed.query(r.pose?.position[0]??r.prop.x,r.pose?.position[2]??r.prop.z,5))if(!records.has(s.id)&&destructionRule(s.prop)){const next=scene.edits.get(s.id)??recordFor(s.id,s.prop,scene.rocks,s.object);records.set(s.id,next);frontier.push(next);}}
    if(reads)for(const id of records.keys())reads.set(id,this.geometryVersions.get(id)??0);
    const nodes:{record:SolidRecord;component?:SolidComponent;points:Point3[];ground:boolean;bounds:[Point3,Point3]}[]=[];
    for(const r of records.values()){
      if(r.removed||r.fall&&!r.fall.settled&&r.id!==changed.id)continue;const edited=r.id===changed.id&&a.action!=='dismantle'||!!r.volume.mask||!!r.volume.clips?.length||!!Object.keys(r.volume.bricks).length;
      let components:SolidComponent[]|undefined;if(edited){const cached=this.componentCache.get(r.id);if(cached?.revision===r.revision)components=cached.components;else{const job=await this.jobs.run({task:'components',source:r.source,state:r.volume,step:isTree(r.prop)||r.prop.kind==='rock'?.05:.025});components=job.result;if((isTree(r.prop)||r.prop.kind==='rock')&&components!.length>1){const precise=await this.jobs.run({task:'components',source:r.source,state:r.volume,step:.025});components=precise.result;}this.componentCache.set(r.id,{revision:r.revision,components:components!});while(this.componentCache.size>16)this.componentCache.delete(this.componentCache.keys().next().value!);}}
      const groups=components??[{points:r.prop.kind==='rock'?scene.rocks[r.prop.variant]:[...r.source.primitives.flatMap(p=>p.type==='box'?boxSupportPoints(p.center,p.half):'a'in p?[p.a,p.b]:[p.bounds[0],p.bounds[1]])]as Point3[],bounds:r.source.bounds}];
      if(!groups.length){const index=patch.solids.findIndex(s=>s.id===r.id);if(index>=0)patch.solids[index]={...r,removed:true};patch.removedBuilds.push(r.id);continue;}
      for(const c of groups){const definition=r.object?objectDefinition(r.object.definitionId):undefined,samples=definition?.attachment==='door'?([.35,1.1,1.9].map(y=>[r.object?.state?.open ? .55 : -.55,y,0])as Point3[]):definition?.supportSamples??c.points,points=samples.map(p=>worldPoint(r,p)),corners=[0,1,2,3,4,5,6,7].map(n=>worldPoint(r,[c.bounds[n&1?1:0][0],c.bounds[n&2?1:0][1],c.bounds[n&4?1:0][2]])),bounds:[Point3,Point3]=[[0,1,2].map(i=>Math.min(...corners.map(p=>p[i])))as Point3,[0,1,2].map(i=>Math.max(...corners.map(p=>p[i])))as Point3];nodes.push({record:r,component:components?c as SolidComponent:undefined,points,ground:!definition?.attachment&&points.some(p=>p[1]<=scene.terrain(p[0],p[2]).height+.055),bounds});}
    }
    for(let pass=0;pass<nodes.length;pass++){let change=false;for(const node of nodes)if(!node.ground)for(const other of nodes)if(other.ground&&other!==node&&other.record.id!==node.record.id&&[0,1,2].every(i=>node.bounds[0][i]<=other.bounds[1][i]+.065&&node.bounds[1][i]>=other.bounds[0][i]-.065)){
      const v=new SparseVolume(other.record.source,other.component?{...other.record.volume,mask:other.component.mask}:other.record.volume);if(node.points.some(p=>materialNear(v,localPoint(other.record,p),.045/other.record.prop.scale))){node.ground=true;change=true;break;}}
      if(!change)break;
    }
    const grouped=new Map<string,typeof nodes>();for(const n of nodes){const list=grouped.get(n.record.id)??[];list.push(n);grouped.set(n.record.id,list);}
    for(const [id,group]of grouped){const falling=group.filter(n=>!n.ground);if(!falling.length)continue;if(group.length===1&&group[0].record.fall)continue;const r=group[0].record,kept=group.filter(n=>n.ground);
      if(a.action==='repair'&&id===changed.id)throw new Error('unsupported-repair');
      const index=patch.solids.findIndex(s=>s.id===id),root={...r,removed:!kept.length,revision:r.revision+(id===changed.id?0:1),volume:{...r.volume,mask:kept.length?mergeMasks(kept.map(n=>n.component?.mask).filter(Boolean)as Record<string,number[]>[]):r.volume.mask}};
      if(index>=0)patch.solids[index]=root;else patch.solids.push(root);if(root.removed)patch.removedBuilds.push(id);
      if(r.object&&objectDefinition(r.object.definitionId).family==='floor')patch.leveling.push(r.object);
      for(let i=0;i<falling.length;i++){const n=falling[i],extent=n.bounds[1].map((v,k)=>v-n.bounds[0][k]);if(isTree(r.prop)&&Math.max(...extent)<.75)continue;const fragmentId=`fragment:${createHash('sha256').update(a.requestId+id+':'+i).digest('hex').slice(0,32)}`;parents?.set(fragmentId,id);patch.solids.push({...r,id:fragmentId,object:undefined,opening:undefined,fragmentOf:r.fragmentOf??id,fragmentBounds:n.component?.bounds??r.source.bounds,revision:1,volume:n.component?{...r.volume,mask:n.component.mask}:r.volume,fall:{velocity:r.fall?.velocity??[0,0,0],angular:r.fall?.angular??(isTree(r.prop)?[.15,0,.12]:[0,0,0]),started:Date.now(),persistent:isTree(r.prop),split:r.fall?.split}});}
    }
  }
  private append(saved:SavedEdit){if(!this.file)return;const fd=openSync(this.file,'a'),size=fstatSync(fd).size;try{const bytes=Buffer.from(JSON.stringify(saved)+'\n');let n=0;while(n<bytes.length)n+=writeSync(fd,bytes,n,bytes.length-n);fsyncSync(fd);}catch(e){ftruncateSync(fd,size);throw e;}finally{closeSync(fd);}}
  apply(patch:WorldPatch,broadcast=true){this.revision=patch.revision;for(const r of patch.solids){const old=this.builds.scene.edits.get(r.id);if(!old||r.volume!==old.volume||r.removed!==old.removed){this.geometryVersions.set(r.id,(this.geometryVersions.get(r.id)??0)+1);this.componentCache.delete(r.id);}this.archive?.forget(r.id);}this.builds.applyWorldPatch(patch);if(broadcast)for(const fn of this.listeners)fn(patch);}
  saveMotion(solids:SolidRecord[]):Promise<void>{const task=this.queue.then(()=>this.performMotion(solids));this.queue=task.then(()=>{},()=>{});return task;}
  private async performMotion(solids:SolidRecord[]){solids=solids.filter(r=>{const current=this.builds.scene.edits.get(r.id);return !current||!(current.removed&&!r.removed)&&current.revision<=r.revision&&!(current.fall?.split&&!r.fall?.split);});if(!solids.length)return;const patch:WorldPatch={revision:this.revision+1,solids,removedBuilds:[],leveling:[],openings:[]},saved:SavedEdit={schema:1,worldKey:this.builds.worldKey,requestId:`physics-${patch.revision}`,fingerprint:'physics',patch};this.append(saved);this.apply(patch);if(++this.records>=128)this.compact();}
  private async cookCollisions(records:SolidRecord[]):Promise<[SolidRecord,import('../shared/volume-collision').CollisionBox[]][]>{const result:[SolidRecord,import('../shared/volume-collision').CollisionBox[]][]=[];for(const r of records)if(!r.removed){const cached=this.collisionCache.get(r.id);if(cached?.revision===r.revision){result.push([r,cached.boxes]);continue;}const job=await this.jobs.run({task:'boxes',source:r.source,state:r.volume,step:isTree(r.prop)?.1:.05});this.collisionCache.set(r.id,{revision:r.revision,boxes:job.result});while(this.collisionCache.size>128)this.collisionCache.delete(this.collisionCache.keys().next().value!);result.push([r,job.result]);}return result;}
  private async prepareCollisions(records:SolidRecord[]){for(const [r,boxes]of await this.cookCollisions(records))this.builds.scene.setDamageCollision(r,boxes);}
  private remember(saved:SavedEdit){this.receipts.set(saved.requestId,{requestId:saved.requestId,fingerprint:saved.fingerprint,data:gzipSync(JSON.stringify(saved)).toString('base64')});while(this.receipts.size>2048)this.receipts.delete(this.receipts.keys().next().value!);}
  hydrateCells(keys:string[]){if(!this.archive)return;const ids=[...this.archive.ids(keys)].filter(id=>!this.builds.scene.edits.has(id));for(const r of this.archive.load(ids))this.builds.scene.edits.set(r.id,r);}
  hydrateNear(x:number,z:number){const cells:string[]=[];for(let iz=-1;iz<=1;iz++)for(let ix=-1;ix<=1;ix++)cells.push(buildCell(x+ix*512,z+iz*512));this.hydrateCells(cells);}
  private pruneResident(){const scene=this.builds.scene;let bytes=[...scene.edits.values()].reduce((n,r)=>n+Object.keys(r.volume.bricks).length*1024+(r.volume.mask?Object.keys(r.volume.mask).length*64:0)+r.source.primitives.length*128,0);for(const [id,r]of scene.edits){if(scene.edits.size<=128&&bytes<=32*1024*1024)break;if(!this.archive?.entries.has(id)||r.fall&&!r.fall.settled)continue;scene.edits.delete(id);scene.damageCollision.delete(id);bytes-=Object.keys(r.volume.bricks).length*1024+(r.volume.mask?Object.keys(r.volume.mask).length*64:0)+r.source.primitives.length*128;}}
  compact(){if(!this.file||!this.checkpoint||!this.archive)return;const scene=this.builds.scene,regions=this.archive.write(this.revision,scene.edits.values()),patch:WorldPatch={revision:this.revision,solids:[],removedBuilds:regions.filter(r=>r.removedBuild).map(r=>r.id),leveling:[...scene.leveling.values()],openings:[...scene.openings].map(([id,kind])=>({id,kind}))};const temp=this.checkpoint+'.tmp',data=JSON.stringify({schema:2,worldKey:this.builds.worldKey,patch,regions,support:[...this.supportRequests.values()],receipts:[...this.receipts.values()]});const fd=openSync(temp,'w');try{writeFileSync(fd,data);fsyncSync(fd);}finally{closeSync(fd);}renameSync(temp,this.checkpoint);writeFileSync(this.file,'');for(const entry of regions)this.archive.register(entry);this.records=0;this.pruneResident();this.archive.clean();this.builds.compact();}
  performanceReport(){const stages=new Set([...this.timings,...this.jobs.metrics].map(s=>s.stage));return {revision:this.revision,residentSolids:this.builds.scene.edits.size,archivedSolids:this.archive?.entries.size??0,receiptBytes:[...this.receipts.values()].reduce((n,r)=>n+r.data.length,0),stages:Object.fromEntries([...stages].map(stage=>{const times=[...this.timings,...this.jobs.metrics].filter(v=>v.stage===stage).map(v=>v.milliseconds).sort((a,b)=>a-b);return [stage,{samples:times.length,meanMs:times.reduce((n,v)=>n+v,0)/times.length,p95Ms:times[Math.floor((times.length-1)*.95)]}];}))};}
  dispose(){this.stopped=true;this.supportRequests.clear();this.jobs.dispose();this.listeners.clear();}
}
function mergeMasks(masks:Record<string,number[]>[]){const result:Record<string,number[]>={};for(const mask of masks)for(const [key,values]of Object.entries(mask)){const v=result[key]??=new Array(16).fill(0);for(let i=0;i<16;i++)v[i]|=values[i];}return result;}

function boxSupportPoints(center:Point3,half:Point3):Point3[]{const points:Point3[]=[];for(let axis=0;axis<3;axis++){const u=(axis+1)%3,v=(axis+2)%3,nu=Math.max(1,Math.ceil(half[u]*2/.2)),nv=Math.max(1,Math.ceil(half[v]*2/.2));for(const side of [-1,1])for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){const p=[...center]as Point3;p[axis]+=half[axis]*side;p[u]+=(i/nu*2-1)*half[u];p[v]+=(j/nv*2-1)*half[v];points.push(p);}}return points;}
