import {SpatialIndex} from '../shared/spatial-index';
import {randomUUID,createHash} from 'node:crypto';
import {BuildStore} from './build-store';
import {DestructionStore} from './destruction-store';
import {FallingSimulation} from './falling';
import {WorldJournal,type WorldCommit} from './journal';
import {Character,CHARACTER,idleInput} from '../shared/character';
import {SimulationEnvironment} from '../shared/simulation';
import {initializePhysics} from '../shared/solid-physics';
import {worldSpawn,safeSpawn} from '../shared/spawn';
import {separatePlayers} from '../shared/player-contact';
import {PROTOCOL_VERSION,WORLD_HZ,INTEREST_CELL,validInput,validCell,type InputStep} from '../shared/network';
import {buildCell,validBuildObject,type BuildObject} from '../shared/object-registry';
import type {WorldConfig} from '../shared/config';
import type {Point3} from '../shared/rocks';
import type {WorldPatch} from '../shared/destruction';
import {solidCells} from '../shared/destruction';
type Session={id:string;nickname:string;character:Character;environment:SimulationEnvironment;inputs:InputStep[];ack:number;received:number;cells:Set<string>;generation:number;pending:number;lastInput:number;inputTimes:Map<number,number>;commands:Promise<void>};
export class WorldRuntime {
 readonly builds:BuildStore;readonly edits:DestructionStore;readonly journal:WorldJournal;readonly epoch=randomUUID();tick=0;
 readonly sessions=new Map<string,Session>();private playerIndex=new SpatialIndex<Session>(INTEREST_CELL);private remembered=new Map<string,{id:string;nickname:string;state:ReturnType<Character['capture']>}>();
 private pendingFingerprints=new Map<string,string>();private receipts=new Map<string,{fingerprint:string;result:any}>();private activations:{apply:()=>void;resolve:()=>void}[]=[];
 private falling?:FallingSimulation;private timer?:ReturnType<typeof setInterval>;private last=performance.now();private accumulator=0;private snapshot=0;private checkpoint=0;private saving=false;private closing=false;private durations:number[]=[];private saves=0;private simulationTime=0;
 constructor(config:WorldConfig,directory: string|undefined,readonly emit:(connection:string,message:any)=>void){
  this.builds=new BuildStore(config);this.journal=new WorldJournal(directory,this.builds.worldKey);
  this.edits=new DestructionStore(this.builds,{append:async c=>{if(c.kind==='edit'&&c.result&&(c.result as any).ok)c={...c,result:{ok:true,requestId:c.requestId,patch:{revision:c.patch!.revision,actionId:c.requestId,solids:[],removedBuilds:[],leveling:[],openings:[]}}};const receiptFingerprint=c.requestId?this.pendingFingerprints.get(c.requestId):undefined;await this.journal.append({...c,receiptFingerprint});if(c.requestId&&c.fingerprint&&c.result)this.rememberReceipt(c.requestId,receiptFingerprint??c.fingerprint,c.result);},loadCells:(keys,revision)=>this.journal.cells(keys,revision),protected:()=>[...this.sessions.values()].map(s=>[...s.character.feet]as Point3),activate:apply=>new Promise(resolve=>this.activations.push({apply,resolve}))});
 }
 async initialize(){await Promise.all([initializePhysics(),this.edits.jobs.warm()]);for(const saved of await this.journal.loadWorld()){this.edits.restore(saved);for(const p of saved.players??[])this.remembered.set(p.id,p);for(const m of saved.motion??[]){const old=this.builds.scene.edits.get(m.id);if(old&&m.revision===old.revision)this.builds.scene.edits.set(m.id,{...old,pose:m.pose,fall:m.fall});}if(saved.requestId&&saved.fingerprint&&saved.result)this.rememberReceipt(saved.requestId,saved.receiptFingerprint??saved.fingerprint,saved.result);}
  this.falling=new FallingSimulation(this.edits,false);this.edits.listeners.add(p=>this.publish(p));this.falling.listeners.add(states=>{for(const s of this.sessions.values())for(const m of states){const r=this.builds.scene.edits.get(m.id);if(r)s.environment.pose(r);}for(const [connection,s]of this.sessions){const relevant=states.filter(m=>{const r=this.builds.scene.edits.get(m.id);return r&&this.relevant(s,r);});if(relevant.length)this.emit(connection,{type:'motion',tick:this.tick,time:this.time(),states:relevant.map(m=>({...m,revision:this.builds.scene.edits.get(m.id)?.revision}))});}});
  this.last=performance.now();this.timer=setInterval(()=>this.advance(),1000/WORLD_HZ);this.timer.unref();this.edits.resumeSupport();
 }
 time(){return this.tick/WORLD_HZ;}
 private rememberReceipt(id:string,fingerprint:string,result:any){this.receipts.set(id,{fingerprint,result});while(this.receipts.size>512)this.receipts.delete(this.receipts.keys().next().value!);}
 private relevant(s:Session,r:any){return solidCells(r).some(k=>s.cells.has(k));}
 private publish(patch:WorldPatch){for(const s of this.sessions.values())for(const r of patch.solids){if(r.removed)s.environment.remove(r.id);else{const collision=this.edits.collision(r.id);if(collision)s.environment.install(r,collision.boxes);}}
   for(const [connection,s]of this.sessions){const solids=patch.solids.filter(r=>this.relevant(s,r)),ids=new Set(solids.map(r=>r.id));const filtered={...patch,solids,removedBuilds:patch.removedBuilds.filter(id=>ids.has(id)),leveling:patch.leveling.filter(o=>s.cells.has(buildCell(o.position[0],o.position[2]))),openings:patch.openings.filter(o=>ids.has(o.id)||this.builds.scene.placed.get(o.id)&&s.cells.has(buildCell(this.builds.scene.placed.get(o.id)!.prop.x,this.builds.scene.placed.get(o.id)!.prop.z)))};
   const objects=(patch.objects??[]).filter(o=>s.cells.has(buildCell(o.position[0],o.position[2])));
   if(solids.length||objects.length||filtered.leveling.length||filtered.openings.length)this.emit(connection,{type:'world',tick:this.tick,buildRevision:this.builds.revision,patch:filtered,objects,collisions:solids.filter(r=>!r.removed).map(r=>({id:r.id,revision:r.revision,boxes:this.edits.collision(r.id)?.boxes??[]}))});}
 }
 async join(connection:string,m:any){if(this.closing)throw new Error('Server shutting down');if(m.version!==PROTOCOL_VERSION)throw new Error('Update required: protocol mismatch');if(typeof m.identity!=='string'||!/^[-a-zA-Z0-9]{16,100}$/.test(m.identity)||typeof m.nickname!=='string'||!m.nickname.trim()||m.nickname.length>24)throw new Error('Choose a nickname of 1–24 characters');if([...this.sessions.values()].some(s=>s.id===m.identity))throw new Error('This browser identity is already connected');
  const environment:SimulationEnvironment=new SimulationEnvironment(this.builds.scene,m.identity,()=>this.playerIndex.query(character.feet[0],character.feet[2],16).map(s=>({id:s.id,feet:s.character.feet})),()=>this.simulationTime),character:Character=new Character(environment),saved=this.remembered.get(m.identity),spawn=saved?.state.feet??worldSpawn(this.builds.scene);await this.edits.prepareNearby(spawn[0],spawn[2]);if(this.closing||[...this.sessions.values()].some(s=>s.id===m.identity)){environment.dispose();throw new Error(this.closing?'Server shutting down':'This browser identity is already connected');}character.spawn(...safeSpawn(this.builds.scene,spawn,[...this.sessions.values()].map(s=>[...s.character.feet]as Point3),!!saved));
  if(saved){const feet=[...character.feet]as Point3;character.restore({...saved.state,feet,velocity:[0,0,0],accumulator:0,jumpHeld:false,jumpBuffer:0,coyote:0,ready:false});}
  const s:Session={id:m.identity,nickname:m.nickname.trim(),character,environment,inputs:[],ack:0,received:0,cells:new Set(),generation:0,pending:0,lastInput:this.tick,inputTimes:new Map(),commands:Promise.resolve()};this.sessions.set(connection,s);this.playerIndex.insert(s.id,s,character.feet[0],character.feet[2],CHARACTER.radius);await this.edits.prepareNearby(character.feet[0],character.feet[2]);for(const r of this.builds.scene.edits.values()){const c=this.edits.collision(r.id);if(c&&!r.removed)environment.install(r,c.boxes);}
  this.emit(connection,{type:'welcome',epoch:this.epoch,version:PROTOCOL_VERSION,worldKey:this.builds.worldKey,tick:this.tick,time:this.time(),id:s.id,state:character.capture()});
 }
 inputs(connection:string,inputs:unknown){const s=this.sessions.get(connection);if(!s||!Array.isArray(inputs)||inputs.length>24||inputs.some(i=>!validInput(i)))throw new Error('Invalid player inputs');for(const input of inputs as InputStep[]){if(input.seq<=s.received)continue;if(input.seq!==s.received+1||s.inputs.length>=120)throw new Error('Input queue exceeded');s.inputs.push(input);s.received=input.seq;}s.lastInput=this.tick;}
 subscribe(connection:string,cells:unknown,generation:number){const s=this.sessions.get(connection);if(!s||!Array.isArray(cells)||cells.length>512||cells.some(c=>!validCell(c))||!Number.isSafeInteger(generation)||generation<=s.generation)throw new Error('Invalid subscription');const [x,,z]=s.character.feet;for(const cell of cells){const [cx,cz]=cell.split(':').map(Number);if(Math.hypot((cx+.5)*512-x,(cz+.5)*512-z)>5500)throw new Error('Subscription is too distant');}s.cells=new Set(cells);s.generation=generation;return {generation,tick:this.tick};}
 async baseline(connection:string,cells:string[],generation:number){const s=this.sessions.get(connection);const current=()=>s&&this.sessions.get(connection)===s&&generation===s.generation&&!cells.some(c=>!s.cells.has(c));if(!current())throw new Error('Obsolete region request');await this.edits.hydrateCells(cells);await this.edits.prepareNearby(s!.character.feet[0],s!.character.feet[2]);if(!current())throw new Error('Obsolete region request');const patch=this.edits.snapshot(cells);const collisions=patch.solids.filter(r=>!r.removed).flatMap(r=>{const c=this.edits.collision(r.id);if(!c)return [];s!.environment.install(r,c.boxes);return [{id:r.id,revision:r.revision,boxes:c.boxes}];});return {...this.builds.snapshot(cells),generation,tick:this.tick,edits:patch,collisions};}
 command(connection:string,m:any){const s=this.sessions.get(connection);if(!s||s.pending>=32||!Number.isSafeInteger(m.inputSeq)||m.inputSeq<0||m.inputSeq>s.received||!['action','build'].includes(m.kind)||!m.request||typeof m.request.requestId!=='string')throw new Error('Invalid command');s.pending++;
  s.commands=s.commands.then(async()=>{const id=m.request.requestId;try{const fingerprint=createHash('sha256').update(JSON.stringify([s.id,m.kind,m.request])).digest('hex'),old=this.receipts.get(id);if(old){if(old.fingerprint!==fingerprint)throw new Error('Request ID was reused');this.emit(connection,{type:'receipt',id,result:old.result});return;}
   while(!this.closing&&s.ack<m.inputSeq)await new Promise(r=>setTimeout(r,5));if(this.closing||!this.sessions.has(connection))throw new Error('Connection closed');
   const feet=[...s.character.feet]as Point3,request={...m.request,sessionId:s.id,feet,eye:[feet[0],feet[1]+CHARACTER.eyeHeight,feet[2]],standing:s.character.grounded&&!s.character.swimming,actionTime:s.inputTimes.get(m.inputSeq)??this.time()*1000};
   this.pendingFingerprints.set(id,fingerprint);const result=m.kind==='action'?await this.edits.action(request):await this.edits.place(request);
   const publicResult=result.ok&&m.kind==='action'?{ok:true,requestId:id,patch:{revision:(result as any).patch.revision,actionId:id,solids:[],removedBuilds:[],leveling:[],openings:[]}}:result;if(result.ok)this.rememberReceipt(id,fingerprint,publicResult);
   this.emit(connection,{type:'receipt',id,result:publicResult});
  }catch(error){this.emit(connection,{type:'receipt',id,result:{ok:false,code:'request',error:error instanceof Error?error.message:String(error)}});}finally{this.pendingFingerprints.delete(id);s.pending--;}});
 }
 private advance(){const now=performance.now(),dt=Math.min(.1,(now-this.last)/1000);this.last=now;this.accumulator+=dt;let catchup=0;while(this.accumulator>=1/WORLD_HZ&&catchup++<3){this.accumulator-=1/WORLD_HZ;const start=performance.now();for(const a of this.activations.splice(0)){a.apply();a.resolve();}this.tick++;
   for(let step=0;step<4;step++){this.simulationTime=(this.tick-1)/WORLD_HZ+step*CHARACTER.timestep;for(const s of [...this.sessions.values()].sort((a,b)=>a.id.localeCompare(b.id))){const input=s.inputs.shift();if(input){s.ack=input.seq;s.inputTimes.set(input.seq,this.simulationTime*1000);while(s.inputTimes.size>480)s.inputTimes.delete(s.inputTimes.keys().next().value!);}s.character.update(CHARACTER.timestep,input?.input??idleInput);this.playerIndex.insert(s.id,s,s.character.feet[0],s.character.feet[2],CHARACTER.radius);this.edits.updateActor(s.id,[...s.character.feet]as Point3);}separatePlayers([...this.sessions.values()].map(s=>({id:s.id,feet:s.character.feet,velocity:s.character.velocity})),(id,delta)=>[...this.sessions.values()].find(s=>s.id===id)!.character.contact(delta));}
   this.falling?.advance(1/WORLD_HZ);this.snapshot+=1/WORLD_HZ;if(this.snapshot>=1/20){this.snapshot-=1/20;for(const [connection,s]of this.sessions)this.emit(connection,{type:'players',epoch:this.epoch,tick:this.tick,time:this.time(),players:this.playerIndex.query(s.character.feet[0],s.character.feet[2],256).filter(p=>p===s||Math.hypot(p.character.feet[0]-s.character.feet[0],p.character.feet[2]-s.character.feet[2])<256).map(p=>({id:p.id,nickname:p.nickname,state:p.character.capture(),ack:p.ack}))});}
   this.checkpoint+=1/WORLD_HZ;if(this.checkpoint>=1&&!this.saving){this.checkpoint=0;this.saving=true;void this.savePlayers().catch(e=>console.error('Player save:',e)).finally(()=>this.saving=false);}this.durations.push(performance.now()-start);if(this.durations.length>300)this.durations.shift();
  }
 }
 private async savePlayers(){const active=[...this.sessions.values()].map(s=>({id:s.id,nickname:s.nickname,state:s.character.capture()}));for(const p of active)this.remembered.set(p.id,p);if(active.length)await this.journal.append({kind:'players',players:active});if(active.length&&++this.saves%120===0)await this.journal.checkpoint([]);if(!active.length)this.edits.evictIdle();for(const s of this.sessions.values())s.environment.retain(r=>this.builds.scene.edits.has(r.id)&&this.relevant(s,r));}
 async leave(connection:string){const s=this.sessions.get(connection);if(!s)return;this.remembered.set(s.id,{id:s.id,nickname:s.nickname,state:s.character.capture()});this.sessions.delete(connection);this.playerIndex.remove(s.id);this.edits.actors.delete(s.id);s.environment.dispose();await this.journal.append({kind:'players',players:[this.remembered.get(s.id)!]});}
 performance(){return {...this.edits.performanceReport(),players:this.sessions.size,tick:this.tick,p95TickMs:[...this.durations].sort((a,b)=>a-b)[Math.floor(this.durations.length*.95)]??0};}
 async close(){this.closing=true;this.falling?.dispose();await Promise.all([...this.sessions.values()].map(s=>s.commands));await this.edits.idle();await this.savePlayers();if(this.timer)clearInterval(this.timer);this.falling?.dispose();await this.journal.checkpoint([...this.edits.checkpoint(),{kind:'players',players:[...this.remembered.values()]},...[...this.receipts].map(([requestId,r])=>({kind:'support' as const,requestId,...r}))]);await this.journal.close();for(const s of this.sessions.values())s.environment.dispose();this.edits.dispose();}
}
