import {chromium} from 'playwright';
import {mkdtempSync,mkdirSync,rmSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import type {AddressInfo} from 'node:net';
import {createWorldServer} from '../server/app';
mkdirSync('artifacts',{recursive:true});const prefix=resolve('artifacts/destruction-browser-'),directory=mkdtempSync(prefix),config=await(await fetch('http://127.0.0.1:5173/api/world')).json(),server=createWorldServer(config,{saveDirectory:directory});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${(server.address()as AddressInfo).port}`;
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-webgpu','--ignore-gpu-blocklist']}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors:string[]=[];
let rejectNext=false;page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/409 \(Conflict\)/.test(m.text()))errors.push(m.text());});
await page.addInitScript(({socket})=>{(window as any).__name=(value:any)=>value;const Native=window.WebSocket;window.WebSocket=class extends Native{constructor(address:string|URL,protocols?:string|string[]){super(String(address).endsWith('/api/events')?socket:String(address),protocols);}}as typeof WebSocket;},{socket:url.replace('http:','ws:')+'/api/events'});
await page.route('**/api/builds**',async route=>{const r=await route.fetch({url:url+new URL(route.request().url()).pathname+new URL(route.request().url()).search});await route.fulfill({response:r});});await page.route('**/api/actions',async route=>{if(rejectNext){rejectNext=false;await new Promise(r=>setTimeout(r,500));await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({ok:false,code:'test',error:'Test rejection'})});return;}const r=await route.fetch({url:url+'/api/actions'});console.log('action',route.request().postData()?.slice(0,160),r.status());await route.fulfill({response:r});});
try{
  await page.goto('http://127.0.0.1:5173/?profile=1');await page.waitForFunction(()=>{const a=(window as any).__island;if(a?.failed)throw new Error(document.getElementById('message')!.textContent!);return a?.player.ready&&a.building.connection==='Connected'&&a.stream.loading===0;},{},{timeout:120000});
  console.log('ready');await page.mouse.click(700,400);await page.waitForTimeout(100);
  const p=await page.evaluate(()=>{const a=(window as any).__island,b=a.building,o=[...a.player.feet];b.select(2);for(let radius=5;radius<25;radius+=4)for(let i=0;i<18;i++){const angle=i*Math.PI*2/18,x=o[0]+Math.cos(angle)*radius,z=o[2]+Math.sin(angle)*radius,h=b.scene.terrain(x,z).height;a.camera.spawn(x,b.scene.terrain(x,z+3).height,z+3);a.player.ready=true;a.player.grounded=true;a.camera.yaw=0;a.camera.pitch=Math.atan2(h-a.camera.position[1],3);b.update(0);if(b.preview?.valid)return [...b.preview.object.position];}throw new Error('No clear wall site');});
  await page.mouse.down();await page.mouse.up();await page.waitForFunction(()=>(window as any).__island.building.pending.size===0);console.log('placed',p);
  await page.keyboard.press('9');await page.evaluate(p=>{const a=(window as any).__island;a.camera.spawn(p[0],a.building.scene.terrain(p[0],p[2]+2).height,p[2]+2);const eye=a.camera.position;a.camera.yaw=0;a.camera.pitch=Math.atan2(p[1]+1.2-eye[1],2);a.building.update(0);},p);await page.waitForTimeout(250);
  await page.waitForFunction(()=>(window as any).__island.stream.loading===0,{},{timeout:120000});await page.evaluate(()=>{const a=(window as any).__island;a.daylight.setAutomatic(false,Date.now()/1000);a.perf.reset();});await page.waitForTimeout(6000);const unchanged=await page.evaluate(()=>(window as any).__island.perf.summary());await page.screenshot({path:'artifacts/destruction-before.png'});await page.mouse.down({button:'right'});await page.waitForTimeout(15);await page.mouse.up({button:'right'});await page.waitForFunction(()=>[...(window as any).__island.building.scene.edits.values()].some((r:any)=>r.revision>0),{},{timeout:30000});await page.waitForFunction(()=>(window as any).__island.building.destruction.pending.size===0,{},{timeout:120000});console.log('brief right-click applied');await page.mouse.down({button:'right'});await page.waitForTimeout(1800);await page.mouse.up({button:'right'});
  await page.waitForFunction(()=>{const a=(window as any).__island;return a.building.destruction.pending.size===0&&a.renderer.resources.damagedObjects>0;},{},{timeout:120000});await page.waitForTimeout(1000);await page.screenshot({path:'artifacts/destruction-wall-cut.png'});
  const cut=await page.evaluate(()=>{const a=(window as any).__island;return {records:[...a.building.scene.edits.values()].map((r:any)=>({id:r.id,revision:r.revision,removed:r.removed,bricks:Object.keys(r.volume.bricks).length})),resources:a.renderer.resources,metrics:a.building.destruction.metrics,stages:Object.fromEntries(a.building.destruction.stages),perf:a.perf.summary(),errors:a.renderer.errors};});console.log('wall cut',cut.records);
  await page.keyboard.down('r');await page.waitForTimeout(1800);await page.keyboard.up('r');await page.waitForFunction(()=>(window as any).__island.building.destruction.pending.size===0,{},{timeout:120000});await page.waitForTimeout(1500);await page.screenshot({path:'artifacts/destruction-wall-repaired.png'});
  const repair=await page.evaluate(()=>{const a=(window as any).__island;return {records:[...a.building.scene.edits.values()].map((r:any)=>({id:r.id,revision:r.revision,removed:r.removed,bricks:Object.keys(r.volume.bricks).length})),resources:a.renderer.resources,errors:a.renderer.errors};});console.log('repair',repair.records);
  await page.waitForFunction(()=>{const d=(window as any).__island.building.destruction;return !d.workerBusy&&d.tasks.size===0;},{},{timeout:120000});await page.evaluate(()=>(window as any).__island.perf.reset());await page.waitForTimeout(6000);const damagedSteady=await page.evaluate(()=>{const a=(window as any).__island;return {frames:a.perf.summary(),editing:a.building.destruction.performanceReport()};});
  const renderComparison=[];for(const mode of ['original','damaged','original']){await page.evaluate(mode=>{const a=(window as any).__island,r=a.renderer;if(mode==='original'){r.__heldDamage??=r.damaged;r.damaged=new Map();}else r.damaged=r.__heldDamage;r.damageGeometryRevision++;r.scenerySignature='';a.perf.reset();},mode);await page.waitForTimeout(4500);renderComparison.push({mode,...await page.evaluate(()=>(window as any).__island.perf.summary())});}await page.evaluate(()=>{const r=(window as any).__island.renderer;r.damaged=r.__heldDamage;r.damageGeometryRevision++;r.scenerySignature='';});
  writeFileSync('artifacts/destruction-validation.json',JSON.stringify({errors,unchanged,cut,repair,damagedSteady,renderComparison,partial:true},null,2));
  const beforeReject=await page.evaluate(()=>JSON.stringify([...(window as any).__island.building.scene.edits.values()].map((r:any)=>r.volume)));rejectNext=true;await page.mouse.down({button:'right'});await page.waitForTimeout(90);await page.mouse.up({button:'right'});await page.waitForFunction(()=>(window as any).__island.building.destruction.pending.size===0,{},{timeout:15000});const afterReject=await page.evaluate(()=>JSON.stringify([...(window as any).__island.building.scene.edits.values()].map((r:any)=>r.volume)));if(beforeReject!==afterReject)throw new Error('Rejected prediction was not rolled back');
  const tree=await page.evaluate(()=>{const a=(window as any).__island,b=a.building,o=[...a.player.feet];b.select(1);for(let i=0;i<6;i++)b.cycle(1);for(let radius=6;radius<25;radius+=4)for(let i=0;i<18;i++){const angle=i*Math.PI*2/18,x=o[0]+Math.cos(angle)*radius,z=o[2]+Math.sin(angle)*radius,h=b.scene.terrain(x,z).height;a.camera.spawn(x,b.scene.terrain(x,z+3).height,z+3);a.player.ready=true;a.player.grounded=true;a.player.swimming=false;a.camera.yaw=0;a.camera.pitch=Math.atan2(h-a.camera.position[1],3);b.update(0);if(b.preview?.valid)return [...b.preview.object.position];}throw new Error('No clear tree site: '+b.preview?.reason+' '+b.definitionId+' '+b.variant);});await page.waitForTimeout(2500);await page.mouse.down();await page.mouse.up();await page.waitForFunction(()=>(window as any).__island.building.pending.size===0,{},{timeout:15000});const treeId=await page.evaluate(()=>{const a=(window as any).__island;return a.building.scene.placed.values().find((s:any)=>s.prop.kind==='birch')?.id;});if(!treeId)throw new Error('Birch placement failed');await page.keyboard.press('9');
  for(const [offset,side] of [[0,1],[0,-1],[-.08,1],[.08,1],[-.08,-1],[.08,-1],[-.16,1],[.16,1],[-.16,-1],[.16,-1]]){await page.evaluate(({tree,offset,side})=>{const a=(window as any).__island;a.camera.spawn(tree[0]+offset,a.building.scene.terrain(tree[0]+offset,tree[2]+side*2).height,tree[2]+side*2);a.camera.yaw=side===1?0:Math.PI;a.camera.pitch=Math.atan2(tree[1]+.45-a.camera.position[1],2);a.building.update(0);},{tree,offset,side});await page.mouse.down({button:'right'});await page.waitForTimeout(1800);await page.mouse.up({button:'right'});await page.waitForFunction(()=>(window as any).__island.building.destruction.pending.size===0,{},{timeout:120000});if(await page.evaluate(id=>[...(window as any).__island.building.scene.edits.values()].some((r:any)=>r.fragmentOf===id),treeId))break;}
  await page.waitForFunction(id=>[...(window as any).__island.building.scene.edits.values()].some((r:any)=>r.fragmentOf===id&&r.pose),treeId,{timeout:120000});await page.waitForTimeout(8000);await page.evaluate(id=>{const a=(window as any).__island,record=[...a.building.scene.edits.values()].find((r:any)=>r.fragmentOf===id&&!r.removed&&r.pose);if(!record)return;const p=record.pose.position;a.camera.spawn(p[0]+4,a.building.scene.terrain(p[0]+4,p[2]+8).height,p[2]+8);a.player.ready=true;const dx=p[0]-a.camera.position[0],dz=p[2]-a.camera.position[2];a.camera.yaw=Math.atan2(dx,-dz);a.camera.pitch=Math.atan2(p[1]+1-a.camera.position[1],Math.hypot(dx,dz));},treeId);await page.waitForTimeout(500);await page.screenshot({path:'artifacts/destruction-tree-fallen.png'});const trees=await page.evaluate(id=>{const a=(window as any).__island;return {pieces:[...a.building.scene.edits.values()].filter((r:any)=>r.fragmentOf===id).map((r:any)=>({id:r.id,removed:r.removed,pose:r.pose,fall:r.fall})),errors:a.renderer.errors,editing:a.building.destruction.performanceReport(),resources:a.renderer.resources};},treeId);
  const serverPerformance=await(await fetch(url+'/api/performance')).json();writeFileSync('artifacts/destruction-validation.json',JSON.stringify({errors,unchanged,cut,repair,damagedSteady,renderComparison,trees,serverPerformance,rollback:true},null,2));console.log('render comparison',renderComparison.map(r=>({mode:r.mode,fps:r.fps,cpu:r.cpu.total?.meanMs,gpu:r.gpu.total?.meanMs})));console.log('tree pieces',trees.pieces,'steady FPS',unchanged.fps,damagedSteady.frames.fps,'errors',errors);if(errors.length||cut.errors.length||repair.errors.length||trees.errors.length)throw new Error(errors.join('\n'));
}catch(error){console.log('failure state',await page.evaluate(()=>{const a=(window as any).__island;return {notice:a?.building.notice,debug:a?.building.destruction.debugReport(),pending:a?.building.destruction.pending.size,taskCount:a?.building.destruction.tasks.size,current:a?.building.destruction.current,errors:a?.renderer.errors,records:[...a?.building.scene.edits.values()??[]].map((r:any)=>({id:r.id,revision:r.revision,removed:r.removed})),browserErrors:[]};}));console.log('browser errors',errors);await page.screenshot({path:'artifacts/destruction-failure.png'});throw error;}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));if(!resolve(directory).startsWith(prefix))throw new Error('Bad artifact path');rmSync(directory,{recursive:true,force:true});}
