import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,mkdirSync,rmSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import type {AddressInfo} from 'node:net';
import {createWorldServer} from '../server/app';
mkdirSync('artifacts',{recursive:true});const prefix=resolve('artifacts/single-client-'),directory=mkdtempSync(prefix),origin='http://127.0.0.1:4117';
const server=createWorldServer({seed:'single-client-check',islandSizeMeters:1024},{saveDirectory:directory,origins:[origin]});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const api=`http://127.0.0.1:${(server.address()as AddressInfo).port}`;
const vite=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','4117','--strictPort'],{env:{...process.env,VITE_API_URL:api},stdio:'pipe'});let output='';vite.stdout.on('data',b=>output+=b);vite.stderr.on('data',b=>output+=b);
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;const errors:string[]=[],report:any={clients:1,liveMultiplayerTested:false};
try{
 for(let i=0;i<200;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));if(i===199)throw new Error('Vite failed: '+output);}
 browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-webgpu','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept('Explorer'));await page.addInitScript(()=>localStorage.setItem('island-z-player-v1',JSON.stringify({id:'browser-single-test-00001',nickname:'Explorer'})));
 await page.goto(origin);const ready=async()=>page.waitForFunction(()=>{const a=(window as any).__island;if(a?.failed)throw new Error(document.getElementById('message')!.textContent!);return a?.multiplayer.connected&&a.player.ready&&a.building.connection==='Connected';},{},{timeout:120000});await ready();
 const before=await page.evaluate(()=>[...(window as any).__island.player.feet]);await page.locator('#world').click({position:{x:100,y:100}});await page.keyboard.press('9');await page.keyboard.down('w');await page.waitForTimeout(1000);await page.keyboard.up('w');await page.waitForTimeout(400);const after=await page.evaluate(()=>[...(window as any).__island.player.feet]);if(Math.hypot(after[0]-before[0],after[2]-before[2])<.2)throw new Error('Authoritative movement did not progress');report.movement={before,after};
 const valid=await page.evaluate(()=>{const a=(window as any).__island,b=a.building;b.select(2);for(const pitch of [-.5,-.65,-.8])for(let i=0;i<16;i++){a.camera.yaw=i*Math.PI/8;a.camera.pitch=pitch;b.update(0);if(b.preview?.valid){b.place();return true;}}return false;});if(!valid)throw new Error('No valid local wall placement');await page.waitForFunction(()=>{const b=(window as any).__island.building;return b.pending.size===0&&b.scene.placed.size>0;},{},{timeout:30000});
 report.build=await page.evaluate(()=>{const a=(window as any).__island;return {objects:a.building.scene.placed.values().map((s:any)=>s.object),metrics:a.multiplayer.metrics};});
 await page.evaluate(async()=>{const a=(window as any).__island,b=a.building,w=b.scene.placed.values()[0].object,p=a.camera.position,dx=w.position[0]-p[0],dy=w.position[1]+1.2-p[1],dz=w.position[2]-p[2];a.camera.yaw=Math.atan2(dx,-dz);a.camera.pitch=Math.atan2(dy,Math.hypot(dx,dz));b.select(8);await b.destruction.stroke();});
 await page.waitForFunction(()=>{const d=(window as any).__island.building.destruction;return d.pending.size===0&&[...d.authoritative.values()].some((r:any)=>r.revision>0);},{},{timeout:30000});await page.waitForFunction(()=>{const d=(window as any).__island.building.destruction;return !d.workerBusy&&[...d.authoritative.values()].every((r:any)=>r.removed||d.generated.get(r.id)===r.revision);},{},{timeout:30000});report.cut=await page.evaluate(()=>{const d=(window as any).__island.building.destruction;return {records:[...d.authoritative.values()].map((r:any)=>({id:r.id,revision:r.revision,bricks:Object.keys(r.volume.bricks).length})),performance:d.performanceReport()};});
 await page.screenshot({path:'artifacts/single-client.png'});await page.keyboard.press('Escape');await page.reload();await ready();await page.waitForFunction(()=>[...(window as any).__island.building.destruction.authoritative.values()].some((r:any)=>r.revision>0),{},{timeout:30000});report.reload=await page.evaluate(()=>{const a=(window as any).__island;return {feet:[...a.player.feet],objects:a.building.scene.placed.size,oxygen:a.player.oxygen,stamina:a.player.stamina};});const gpuErrors=await page.evaluate(()=>(window as any).__island.renderer.errors);if(gpuErrors.length)throw new Error(gpuErrors.join('\n'));if(errors.length)throw new Error(errors.join('\n'));report.server=await(await fetch(api+'/api/performance',{headers:{Origin:origin}})).json();report.passed=true;
}finally{report.errors=errors;writeFileSync('artifacts/single-client-validation.json',JSON.stringify(report,null,2));await browser?.close();vite.kill();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));if(!directory.startsWith(prefix))throw new Error('Unexpected test save path');rmSync(directory,{recursive:true,force:true});}
console.log(JSON.stringify(report,null,2));
