import {chromium,type Route} from 'playwright';
import {mkdirSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import type {AddressInfo} from 'node:net';
import {createWorldServer} from '../server/app';
mkdirSync('artifacts',{recursive:true});const prefix=resolve('artifacts/catalogue-browser-save-'),directory=mkdtempSync(prefix);
const config=await(await fetch('http://127.0.0.1:5173/api/world')).json();let server=createWorldServer(config,{saveDirectory:directory});
let testPort=0;async function listen(){await new Promise<void>(r=>server.listen(testPort,'127.0.0.1',r));testPort=(server.address()as AddressInfo).port;return `http://127.0.0.1:${testPort}`;}let serverUrl=await listen();
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-webgpu','--ignore-gpu-blocklist']}),page=await browser.newPage({viewport:{width:1600,height:1000}}),errors:string[]=[],reports:unknown[]=[];let rejectNext=false,delayNext=false;
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/409 \(Conflict\)/.test(m.text()))errors.push(m.text());});
await page.addInitScript(({socket})=>{const Native=window.WebSocket;window.WebSocket=class extends Native{constructor(address:string|URL,protocols?:string|string[]){super(String(address).endsWith('/api/events')?socket:String(address),protocols);}}as typeof WebSocket;},{socket:serverUrl.replace('http:','ws:')+'/api/events'});
await page.route('**/api/builds**',async(route:Route)=>{const url=new URL(route.request().url());if(route.request().method()==='POST'){if(rejectNext){rejectNext=false;await new Promise(r=>setTimeout(r,500));await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({ok:false,code:'overlap',error:'Test rejection'})});return;}if(delayNext){delayNext=false;await new Promise(r=>setTimeout(r,500));}}const response=await route.fetch({url:serverUrl+url.pathname+url.search});await route.fulfill({response});});
async function ready(){await page.waitForFunction(()=>{const a=(window as any).__island;if(a?.failed)throw new Error(document.getElementById('message')!.textContent!);return a?.player.ready&&a.building.connection==='Connected'&&a.stream.loading===0&&a.stream.pending.length===0;},{},{timeout:120000});}
async function aim(target:number[],feet?:number[]){await page.evaluate(({target,feet})=>{const a=(window as any).__island;if(feet){const ground=a.building.scene.terrain(feet[0],feet[2]).height;a.camera.spawn(feet[0],feet[1]??a.building.scene.standingHeight(feet[0],feet[2],ground),feet[2]);}const p=a.camera.position;a.camera.yaw=Math.atan2(target[0]-p[0],p[2]-target[2]);a.camera.pitch=Math.atan2(target[1]-p[1],Math.hypot(target[0]-p[0],target[2]-p[2]));a.building.update(0);},{target,feet});await page.waitForTimeout(250);}
async function confirm(){await page.mouse.down();await page.mouse.up();await page.waitForFunction(()=>(window as any).__island.building.pending.size===0,{},{timeout:12000});await page.waitForTimeout(200);}
async function state(label:string){const r=await page.evaluate(label=>{const a=(window as any).__island;return {label,objects:a.building.scene.placed.values().map((s:any)=>s.object),preview:a.building.preview,feet:[...a.player.feet],errors:a.renderer.errors,resources:a.renderer.resources};},label);reports.push(r);console.log(JSON.stringify({label,objects:r.objects.length,preview:r.preview?.code,errors:r.errors}));return r;}
try{
  await page.goto('http://127.0.0.1:5173/?profile=1');await ready();await page.locator('#world').click({position:{x:800,y:400}});await page.waitForFunction(()=>!!document.pointerLockElement);
  await page.keyboard.press('1');const first=await page.evaluate(()=>(window as any).__island.building.variant);await page.keyboard.press('e');const next=await page.evaluate(()=>(window as any).__island.building.variant);if(next===first)throw new Error('Q/E did not cycle rocks');await page.keyboard.press('2');await page.keyboard.press('1');if(await page.evaluate(()=>(window as any).__island.building.variant)!==next)throw new Error('Reselection changed the choice');await page.keyboard.press('q');if(await page.evaluate(()=>(window as any).__island.building.variant)!==first)throw new Error('Backward cycling failed');
  await page.keyboard.press('4');await page.evaluate(()=>{const a=(window as any).__island;a.camera.pitch=-.55;for(let i=0;i<72;i++){a.camera.yaw=i*Math.PI*2/72;a.building.update(0);if(a.building.preview?.valid)return;}throw new Error('No clear floor site: '+a.building.preview?.reason);});
  delayNext=true;await page.mouse.down();await page.mouse.up();await page.waitForFunction(()=>(window as any).__island.building.pending.size===1);const pending=await state('optimistic-floor');if(!pending.objects.some((o:any)=>o.definitionId==='floor-wood'))throw new Error('No optimistic floor');await page.waitForFunction(()=>(window as any).__island.building.pending.size===0);const floor=(await state('confirmed-floor')).objects[0];await page.keyboard.press('9');await page.screenshot({path:'artifacts/catalogue-floor.png'});
  const [x,y,z]=floor.position;await aim([x+1.49,y+.20,z],[x+4,null as any,z+3]);await page.keyboard.press('4');await page.keyboard.press('e');await page.waitForTimeout(200);let s=await state('stone-floor-preview');if(!s.preview?.valid||s.preview.object.support.kind!=='floor')throw new Error(s.preview?.reason);await confirm();await page.keyboard.press('9');
  await aim([x,y+.20,z+1.4],[x,null as any,z+4]);await page.keyboard.press('3');await page.waitForTimeout(250);s=await state('wall-on-floor-preview');if(!s.preview?.valid)throw new Error(s.preview?.reason);await confirm();const wall=(await state('wall-on-floor')).objects.find((o:any)=>o.definitionId==='wall-wood');
  await aim([wall.position[0],wall.position[1]+1,wall.position[2]]);await page.keyboard.press('8');await page.waitForTimeout(200);s=await state('door-preview');if(!s.preview?.valid)throw new Error(s.preview?.reason);await page.screenshot({path:'artifacts/catalogue-door-preview.png'});
  // A rejected opening must restore the intact wall, not leave a cut behind.
  rejectNext=true;await page.mouse.down();await page.mouse.up();await page.waitForFunction(()=>(window as any).__island.building.pending.size===1);await page.waitForFunction(()=>(window as any).__island.building.pending.size===0);if(await page.evaluate(id=>(window as any).__island.building.scene.placed.get(id).prop.aperture,wall.id))throw new Error('Rejected door left an opening');await page.waitForTimeout(510);await confirm();
  const door=(await state('door-confirmed')).objects.find((o:any)=>o.definitionId==='door-wood');if(!door)throw new Error('Door did not save');await page.keyboard.press('9');await aim([wall.position[0],wall.position[1]+1,wall.position[2]],[wall.position[0],null as any,wall.position[2]+2]);await page.keyboard.press('f');await page.waitForFunction(id=>(window as any).__island.building.scene.placed.get(id).object.state.open,door.id);await page.waitForFunction(()=>(window as any).__island.building.pending.size===0);await page.screenshot({path:'artifacts/catalogue-open-door.png'});
  await page.evaluate(()=>{const a=(window as any).__island;a.camera.yaw=0;a.camera.pitch=0;});await page.keyboard.down('w');await page.waitForTimeout(1100);await page.keyboard.up('w');const walked=await state('walked-through-door');if(walked.feet[2]>=wall.position[2])throw new Error('Door opening blocked walking');
  await aim([wall.position[0]-.55,wall.position[1]+1,wall.position[2]+.55],[wall.position[0],y+.2,wall.position[2]-1.8]);await page.keyboard.press('f');await page.waitForFunction(id=>!(window as any).__island.building.scene.placed.get(id).object.state.open,door.id);await page.waitForFunction(()=>(window as any).__island.building.pending.size===0);
  await aim([wall.position[0]+1,wall.position[1]+1.5,wall.position[2]],[wall.position[0]+1,null as any,wall.position[2]+3]);await page.keyboard.press('6');await page.keyboard.press('e');await page.waitForTimeout(150);s=await state('wall-torch-preview');if(!s.preview?.valid)throw new Error(s.preview?.reason);await confirm();await page.keyboard.press('9');
  // Roof at wall top, followed by another snapped roof edge.
  await aim([wall.position[0],wall.position[1]+2.25,wall.position[2]],[wall.position[0],null as any,wall.position[2]+4]);await page.keyboard.press('5');await page.waitForTimeout(150);s=await state('roof-preview');if(!s.preview?.valid)throw new Error(s.preview?.reason);await confirm();await page.keyboard.press('9');
  const roof=(await state('roof-connected')).objects.find((o:any)=>o.definitionId==='roof-wood');await aim([roof.position[0]+1.49,roof.position[1]+.20,roof.position[2]],[roof.position[0]+4,null as any,roof.position[2]]);await page.keyboard.press('5');await page.keyboard.press('e');await page.waitForTimeout(200);s=await state('stone-roof-preview');if(!s.preview?.valid||s.preview.object.support.kind!=='roof')throw new Error(s.preview?.reason);await confirm();await page.keyboard.press('9');
  // Place each new Blender furnishing and wall through canonical validation.
  const ids=['bed','table','chair','campfire','wall-stone','wall-log','wall-brick'];
  for(const id of ids){const result=await page.evaluate(id=>{const a=(window as any).__island,b=a.building,origin=[...a.player.feet];const slot=id.startsWith('wall-')?2:id==='campfire'?5:6;b.select(slot);for(let n=0;n<8&&b.definitionId!==id;n++)b.cycle(1);for(let radius=9;radius<32;radius+=5)for(let i=0;i<18;i++){const angle=i*Math.PI*2/18,x=origin[0]+Math.cos(angle)*radius,z=origin[2]+Math.sin(angle)*radius,fy=b.scene.terrain(x,z+4).height;a.camera.spawn(x,fy,z+4);a.player.ready=true;a.player.grounded=true;const target=b.scene.terrain(x,z).height;a.camera.yaw=0;a.camera.pitch=Math.atan2(target-a.camera.position[1],4);b.update(0);if(b.preview?.valid)return {position:b.preview.object.position};}throw new Error('No clear placement for '+id+': '+b.preview?.reason);},id);await ready();await page.waitForTimeout(150);if(!(await page.evaluate(()=>(window as any).__island.building.preview?.valid)))throw new Error('Preview lost for '+id);await confirm();await state(id);await page.keyboard.press('9');await aim([result.position[0],result.position[1]+.65,result.position[2]],[result.position[0]+3,null as any,result.position[2]+4]);await page.screenshot({path:`artifacts/catalogue-${id}.png`});}
  // Attach a window to an existing stone wall with a real automatically cut hole.
  const stone=(await state('furnishings')).objects.find((o:any)=>o.definitionId==='wall-stone');await aim([stone.position[0],stone.position[1]+1.5,stone.position[2]],[stone.position[0],null as any,stone.position[2]+4]);await page.keyboard.press('8');await page.keyboard.press('e');await page.keyboard.press('e');await page.waitForTimeout(200);s=await state('window-preview');if(!s.preview?.valid)throw new Error(s.preview?.reason);await confirm();await page.keyboard.press('9');await page.screenshot({path:'artifacts/catalogue-window.png'});
  await page.keyboard.press('Escape');await page.evaluate(()=>{const slider=document.getElementById('daylight-time')as HTMLInputElement;slider.value='0';slider.dispatchEvent(new Event('input',{bubbles:true}));});const fire=(await state('complete')).objects.find((o:any)=>o.definitionId==='campfire');await aim([fire.position[0],fire.position[1]+.35,fire.position[2]],[fire.position[0]+2.5,null as any,fire.position[2]+3]);await page.screenshot({path:'artifacts/catalogue-campfire-night.png'});
  server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));server=createWorldServer(config,{saveDirectory:directory});serverUrl=await listen();await page.reload();await ready();const restored=await state('restored');if(restored.objects.length!==15)throw new Error('Catalogue save count failed: '+restored.objects.length);if(!restored.objects.find((o:any)=>o.id===door.id&&o.state?.open===false))throw new Error('Door state did not restore');if(restored.errors.length||errors.length)throw new Error([...errors,...restored.errors].join('\n'));writeFileSync('artifacts/catalogue-validation.json',JSON.stringify({errors,reports},null,2));
}finally{await browser.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));if(!resolve(directory).startsWith(prefix))throw new Error('Unexpected test directory');rmSync(directory,{recursive:true,force:true});}
